```{r oncoprint-top100-plus-panel-data-generation, eval = FALSE}
load("../data/gdc_reactome_path_analysis.Rda") ## load data
umap_cancertype <- data.table::fread("../data/umap_3d_coors.tsv")
load("../data/moderate_enrich_prob.Rda") 
load("../data/kelly.colours.rda")

### Figure A - oncoprint style top 100 pathways

top100path <- gdc_reactome_path_analysis %>% rowSums() %>% as.data.frame() %>% rownames_to_column(var = "path_name") %>% arrange(desc(.)) %>% .[1:100,] %>% .[, "path_name"] ## getting the top100 mutated pathways in class

top100path <- gdc_reactome_path_analysis[top100path, ] ## selecting the top 100 paths

top100path[top100path == "1"] <- "MUT" ## categorize boolean values
top100path[top100path == "0"] <- " "

onco_res <- oncoPrint(top100path,
                      remove_empty_columns = F, remove_empty_rows = F,
                      right_annotation = NULL, top_annotation = NULL)
  
clust_col_order <- names(top100path[,onco_res@column_order])
path_row_order <- rownames(top100path[onco_res@row_order,])

onco_ggplot <- gdc_reactome_path_analysis %>% .[rownames(.) %in% path_row_order,] %>% ## only include the top 10 paths
  rownames_to_column(var = "path_name") %>% ## path_name to col
  gather(., key = "sample_id", value = "mutation_status", -path_name) %>% ## wide to long format
  mutate(path_name = factor(.$path_name, levels = c(rev(path_row_order))), ## factor to force oncoprint order
         sample_id = factor(.$sample_id, levels = c(clust_col_order)))
save(onco_ggplot, file = "onco_ggplot.Rda")

### Figure B - Pathway enrichment by cluster

## Getting the total number of tumor samples in each cluster
n_tumor_in_clust <- as.data.frame(table(umap_cancertype$clust_knn)) %>% ## table the number of tumors in each cluster
  'colnames<-' (c("clust", "tot_n_clust")) %>% ## move cluster number to rownames
  mutate(clust = as.character(clust)) ## convert factor to character

## Organizing rBeta data
load("../data/gdc_reactome_path_analysis.Rda")
clust_group <- n_tumor_in_clust$clust
cluster_path_count <- list()
for(n in clust_group) {
  sample_id <- umap_cancertype %>% filter(clust_knn == n) %>% ## filter for tumor class
    .[,.$sample_id] ## get sample_ids
  path_mutation <- gdc_reactome_path_analysis %>% .[,names(.) %in% sample_id] %>% ## getting the tumor samples from path analysis
    rowSums() %>% as.data.frame() %>% ## getting the observed mutation count of tumor class
    'colnames<-' (n) ## change colname to cluster number
  cluster_path_count[[n]] <- path_mutation
  rm(path_mutation, sample_id, n)
  gc()
}
cluster_path_count <- as.data.frame(do.call(cbind, cluster_path_count)) ## Combine the list together

global_path_mut <- cluster_path_count %>% rowSums() %>% as.data.frame() %>% ## global pathway mutation count
  .[rep(1:ncol(.), each = max(umap_cancertype$clust_knn))] %>% ## replicate the column 0 times for the 10 tumor classes
  'colnames<-' (clust_group) %>% ## rename column with tumor class
  rownames_to_column(var = "path") %>% ## move rownames to column (pathways) %>%
  gather(., key = "clust", value = "global_mut", -path)

rbeta_path_analysis <- cluster_path_count %>% rownames_to_column(var="path") %>%
  gather(key = "clust", value = "clust_mut", -path) %>% ## Wide to long format
  left_join(., global_path_mut, by = c("path", "clust")) %>% ## add global mutation count 
  left_join(., n_tumor_in_clust, by = "clust") %>% ## add total number of tumor samples per clust 
  mutate(global_sample = sum(n_tumor_in_clust$tot_n_clust)) ## add total number of tumor samples

rm(global_path_mut, cluster_path_count, n_tumor_in_clust, clust_group, tumor_clusters, gdc_reactome_path_analysis)
gc()

enrich_prob_uncertainity_in_bg <- data.frame(path = rbeta_path_analysis$path,
                                            clust = rbeta_path_analysis$clust,
                                            fg_mut = rbeta_path_analysis$clust_mut,  
                                            fg_not_mut = rbeta_path_analysis$tot_n_clust - rbeta_path_analysis$clust_mut,
                                            bg_mut = rbeta_path_analysis$global_mut,
                                            bg_not_mut = rbeta_path_analysis$global_sample - rbeta_path_analysis$global_mut
                                            )

## Calculating the foreground and background mutation rate for each cluster
fg_mut_rate <- list()
bg_mut_rate <- list()
for(n in 1:max(as.numeric(unique(enrich_prob_uncertainity_in_bg$clust)))) {
  df <- subset(enrich_prob_uncertainity_in_bg, clust == n) ## Only include pathways in selected cluster
  fg_denominator <- nrow(df) * (df$fg_mut[1] + df$fg_not_mut[1]) ## n_path * tot_n_clust
  fg_numerator <- sum(df$fg_mut) ## sum of pathway mutation in selected cluster
  bg_denominator <- nrow(df) * (df$bg_mut[1] + df$bg_not_mut[1]) ## n_path * tot_n_clust
  bg_numerator <- sum(df$bg_mut) ## sum of no pathway mutation in selectedcluster
  fg_mut_rate[[n]] <- fg_numerator / fg_denominator ## calculate mutation rate and store in list
  bg_mut_rate[[n]] <- bg_numerator / bg_denominator
  rm(df)
}

fg_mut_rate <- fg_mut_rate %>% do.call(rbind, .) %>% as.data.frame() %>% ## rbind the mut rates from list
  'colnames<-' ("fg_mut_rate") %>% ## rebind col names
  rownames_to_column(var = "clust") ## move rownames to col
bg_mut_rate <- bg_mut_rate %>% do.call(rbind, .) %>% as.data.frame() %>% ## rbind the mut rates from list
  'colnames<-' ("bg_mut_rate") %>% ## rebind col names
  rownames_to_column(var = "clust") ## move rownames to col

enrich_prob_uncertainity_in_bg <- enrich_prob_uncertainity_in_bg %>% left_join(., fg_mut_rate, by = "clust") %>% 
  left_join(., bg_mut_rate, by = "clust") %>% ## add fg and bg mut rate to enrich df
  mutate(rel_odds = .$fg_mut_rate / .$bg_mut_rate) %>% ## calculating relative odds ratio
  mutate(denominator = (.$bg_mut * .$rel_odds) + (.$bg_not_mut / .$rel_odds)) %>%
  mutate(x_adj =(.$fg_mut + .$fg_not_mut) * (.$bg_mut * .$rel_odds) / .$denominator) %>%
  mutate(y_adj = (.$fg_mut + .$fg_not_mut) - .$x_adj)
rm(fg_mut_rate, bg_mut_rate, rbeta_path_analysis)
gc()

## beta distribution for 1e5 simulations for foreground and background
moderate_fg <- apply(enrich_prob_uncertainity_in_bg[,c("fg_mut", "fg_not_mut")], MARGIN = 1, function(x) {
  rbeta(n = 1e5, shape1=x["fg_mut"], shape2=x["fg_not_mut"]) 
})

moderate_bg <- apply(enrich_prob_uncertainity_in_bg[,c("x_adj", "y_adj")], MARGIN = 1, function(x) {
  rbeta(n = 1e5, shape1=x["x_adj"], shape2=x["y_adj"])
})

## ModerateEnrichment probability 
prob <- moderate_fg > moderate_bg ## boolean data
mean_prob <- apply(prob, MARGIN = 2, function(x) {
  mean(x) ## calculating the mean probability
})
rm(prob)
gc()
## Moderate Difference
CI <- 0.025 ## setting a 95% confidence interval

diff_fg_bg <- moderate_fg - moderate_bg ## Calculating the difference between fg and bg for the next function 
rm(moderate_fg, moderate_bg)
gc()

sig_fg_bg <- as.data.frame(apply(diff_fg_bg, MARGIN = 2, function(x) {
  sum(x < 0 ) ## out of 1e5 simulations, how many times is fg-bg less than 0
}))
quant_diff <- t(apply(diff_fg_bg, MARGIN = 2, function(x) {
  quantile(x, c(CI, 0.5, 1-CI)) ## calculating the 1st quantile, median, and 3rd quantile
}))

moderate_enrich_prob <- data.frame(path = enrich_prob_uncertainity_in_bg$path,
                                   clust = enrich_prob_uncertainity_in_bg$clust,
                                   probability = mean_prob, ## probabilty of pathway mutation
                                   signif = sig_fg_bg[,1], ## how many times fg-bg is less than 0
                                   difference = quant_diff[,2], ## effect size
                                   lower = quant_diff[,1], ## 1st quantile
                                   upper = quant_diff[,3]) ## 3rd quantile
rm(enrich_prob_uncertainity_in_bg, mean_prob, quant_diff, sig_fg_bg, diff_fg_bg)
gc()
save(moderate_enrich_prob, file = "../data/moderate_enrich_prob.Rda") ## save result

## Processing data for effect size heatmap
diff_heatmap <- moderate_enrich_prob %>% dplyr::select(path, clust, difference) %>% ## select relevant column
  spread(., key = "clust", value = "difference") %>% ## long to wide format
  remove_rownames() %>% column_to_rownames(var = "path") ## pathway names to rownames

## Determining pathway order for heatmap
effect_size <- pheatmap(diff_heatmap,
         cluster_cols = T,
         cluster_rows = T,
         clustering_method = "ward.D2")
## Extracting row order from pheatmap
effect_row_order <- effect_size$tree_row$order
effect_row_order <- diff_heatmap %>% .[effect_row_order,] %>% rownames() 

## Revert df back to long format
effect_heatmap <- diff_heatmap %>% rownames_to_column(var = "path_name") %>%  ## pathway names to column
  gather(., key = "cluster", value = "effect_size", -path_name)  ## wide to long

## Factor column to force order when generating plot
effect_heatmap$path_name <- factor(effect_heatmap$path_name, levels = c(rev(effect_row_order)))  ## pathway name ordering
effect_heatmap$cluster <- factor(effect_heatmap$cluster, levels = c(1:max(as.numeric(effect_heatmap$cluster)))) ## cluster ordering
effect_segments <- c(seq(from = -1, -0.2, 0.2), -0.0001, 0.0001, seq(from = 0.2, to = 1, by = 0.2)) ## Creating breaks for heatmap legend (color scale)

effect_heatmap <- effect_heatmap %>% mutate(discrete_color = case_when( ## create discrete variable using continuous
  effect_size > effect_segments[1] & effect_size <= effect_segments[2] ~ "1",
  effect_size > effect_segments[2] & effect_size <= effect_segments[3] ~ "2",
  effect_size > effect_segments[3] & effect_size <= effect_segments[4] ~ "3",
  effect_size > effect_segments[4] & effect_size <= effect_segments[5] ~ "4",
  effect_size > effect_segments[5] & effect_size <= effect_segments[6] ~ "5",
  effect_size > effect_segments[6] & effect_size <= effect_segments[7] ~ "6",
  effect_size > effect_segments[7] & effect_size <= effect_segments[8] ~ "7",
  effect_size > effect_segments[8] & effect_size <= effect_segments[9] ~ "8",
  effect_size > effect_segments[9] & effect_size <= effect_segments[10] ~ "9",
  effect_size > effect_segments[10] & effect_size <= effect_segments[11] ~ "10",
  effect_size > effect_segments[11] & effect_size <= effect_segments[12] ~ "11"
))
effect_heatmap$discrete_color <- factor(effect_heatmap$discrete_color, levels = c(1:11)) ## Factor order the discrete color

save(effect_heatmap, file = "../data/effect_heatmap.Rda")

### Figure C - barplot panel

enrich_pathways <- moderate_enrich_prob %>%
  group_by(clust) %>% 
  filter(difference > 0.3 & signif <= 2500) %>% ## Filter pathways that have an effect size > 0.30 with a 95% CI (signif 2500/1e5)
  mutate(pathway = make_clean_names(path)) %>% 
  rename(clust_knn = "clust") %>%  ## rename clust column to clust_knn
  select(clust_knn, pathway) %>% ## select relevant columns
  mutate(clust_knn = as.numeric(clust_knn)) %>%
  mutate(specific = TRUE) ## Add "specific" column with values TRUE

pathway_counts <- umap_cancertype %>%
  left_join(t(gdc_reactome_path_analysis) %>% ## combine umap_cancertype and gdc_path_analysis by sample_id
              as.data.frame() %>% 
              clean_names() %>% 
              rownames_to_column("sample_id")) %>% 
  group_by(clust_knn) %>% 
  summarise(total = n(), across(intrinsic_pathway_for_apoptosis:signaling_by_the_b_cell_receptor_bcr, sum)) %>% ## Calculate the total_n_clust and total pathway mutation across cluster
  mutate(across(intrinsic_pathway_for_apoptosis:signaling_by_the_b_cell_receptor_bcr, ~ .x / total)) %>% ## Divide sum mutation of cluster / total_n_clust to get percent mutation
  select(-total) %>% ## Remove total column
  pivot_longer(-clust_knn, names_to = "pathway", values_to = "proportion") %>% ## wide to long format
  group_by(clust_knn) %>% 
  filter(pathway %in% enrich_pathways$pathway) %>% ## only include pathways that are enriched
  left_join(enrich_pathways %>% select(clust_knn, pathway, specific), by = c("clust_knn", "pathway"))

pathway_counts[is.na(pathway_counts$specific), ]$specific <- FALSE ## Clusters not enriched for a pathway (NA) convert to FALSE

## Determine the order of pathways on the barplot
pathway_mat <- pathway_counts %>%
  select(-specific) %>%
  pivot_wider(names_from = pathway, values_from = proportion) %>% ## long to wide format
  ungroup() %>%
  select(-clust_knn) %>%
  as.matrix()

pathway_dist <- dist(t(pathway_mat)) ## Computing distance matrix of all values
pathway_clust <- as.hclust(rev(as.dendrogram(seriate(pathway_dist, method = "OLO_ward")[[1]]))) ## cluster pathways based on distance matrix
pathway_counts$pathway <- factor(pathway_counts$pathway, levels = colnames(pathway_mat)[pathway_clust$order]) ## force pathway order by factoring

bp.cluster.colors <- c(kelly.colours[3:12], "gray15") ## Color scheme for plot
names(bp.cluster.colors) <- 1:11 ## Cluster 11 is 

pathway_counts1 <- pathway_counts %>%
  mutate(color = case_when(specific ~ clust_knn, TRUE ~ 11)) %>% ## Color: specific == FALSE is 11; specific == TRUE is its cluster
  mutate(color = factor(color)) 
save(pathway_counts, bp.cluster.colors, file = "barplot_pathways_fig2b.rda")
```

```{r figure-5-plot, fig.align= 'center', fig.height= 7, fig.width = 7}

### Figure A - Waterfall plot of top 100 mutated pathways
load("../data/onco_ggplot.Rda") ## load data
onco_color <- c("0" = "grey", "1" = "firebrick3") ## color scheme for oncoprint

fig5A <- ggplot(data = onco_ggplot, aes(x=sample_id, y=path_name)) + 
  geom_tile(aes(fill = as.character(mutation_status))) +
  scale_fill_manual(values = onco_color) +
  theme_classic() +
  xlab("Pan-Cancer (n=7,607 tumor samples)") +
  ylab("377 pathways") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        legend.position = "none")

### Figure B - Effect size heatmap
load("../data/effect_heatmap.Rda") ## load data

## Function to duplicate discrete axis labels
guide_axis_label_trans <- function(label_trans = identity, ...) {
  axis_guide <- guide_axis(...)
  axis_guide$label_trans <- rlang::as_function(label_trans)
  class(axis_guide) <- c("guide_axis_trans", class(axis_guide))
  axis_guide
}

guide_train.guide_axis_trans <- function(x, ...) {
  trained <- NextMethod()
  trained$key$.label <- x$label_trans(trained$key$.label)
  trained
}

fig5B <- ggplot(data = effect_heatmap, aes(y = cluster, x = path_name)) +
  geom_tile(size = 1, aes(fill = effect_size)) +
  scale_fill_fermenter( ## custom color scale
    type = "div",
    palette = "PuOr",
    n.breaks = 12,
    limits = c(-1, 1), ## Set scale range
    name = "Effect Size",
    labels = c(-1, "", 0.5, "", "", 0, "", "", 0.5, "", 1)
  ) +
  facet_wrap(~cluster, ncol = 1, strip.position = "right", scales = "free_y") + ## facet by cluster
  guides(fill = guide_colorsteps(title.position = "top", title.hjust = 0.5)) +
  xlab("377 pathways, ward.D2 clustered") +
  ylab("Clusters") +
  scale_x_discrete(position = "top") + ## move x labels to top
  guides(y.sec = guide_axis_label_trans(~ paste(.x))) + ## Duplicate axis.text on right side (cluster)
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(), ## turn off y-axis text
    axis.title.x = element_text(size = 10),
    axis.title.y = element_text(size = 10),
    axis.ticks = element_blank(),
    strip.text.y = element_text(size = 10, hjust = .5),
    strip.text.y.right = element_text(angle = 0), ## Fix orientation of dupped right y-axis text
    strip.background = element_blank(),
    panel.background = element_blank(),
    panel.spacing = unit(0, "lines"),
    ## legend parameters
    legend.position = "bottom",
    legend.key.height = unit(0.3, "lines"),
    legend.text = element_text(size = 5),
    legend.title = element_text(size = 5),
    legend.margin=margin(0,0,0,0),
    legend.box.margin=margin(-10,-10,0,-10)
  )

### Figure B - Effect size heatmap
load("../data/barplot_pathways_fig2b.rda") ## load data
fig5C <- pathway_counts %>% ggplot(aes(x = pathway, y = proportion, fill = color)) +
  geom_col() +
  facet_wrap(~clust_knn, ncol = 1, strip.position = "right") + ## facet by cluster and move facet label to the right
  ylab("Proportion of mutated samples") +
  xlab("Significant pathways") +
  theme_classic() +
  scale_fill_manual(values = bp.cluster.colors) +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.title.x = element_text(size = 10),
    axis.title.y = element_text(size = 10),
    axis.ticks = element_blank(),
    axis.line = element_blank(),
    strip.text.y.right = element_text(angle = 0),
    strip.background = element_blank(),
    legend.position = "none"
  )

## Layout for plots using patchwork
layout <- '
AAABBBB
AAABBBB
AAABBBB
AAACCCC
AAACCCC
AAACCCC
AAACCCC
'

fig2A + fig2B + fig2C + plot_layout(design = layout) + plot_annotation(tag_levels = "A")
```