```{r figure-4-data-generation, eval = FALSE}
tumor_clusters <- fread("../data/umap_2d_3d_coors.tsv") ## load in data
load("../data/gene2_level2_lookup.Rda")
load("../data/pathname2level2.Rda")
load("../data/gdc_reactome_path_analysis.Rda")
load("../data/moderate_enrich_prob.Rda")
load("../data/gene_data.Rda")

## Parameters ##
filtered_class <- c(6,7) ## filtering for only class 6 and 7 samples
n_path <- 10 ## looking at the top10 path
enrich_cutoff <- 0.30
################

## Data Generation ##
class_spec <- tumor_clusters %>% dplyr::select(V1, knn_clust) %>% filter(knn_clust %in% filtered_class) %>% .[,.$V1] ## sample_id for class specific

toppath <- moderate_enrich_prob %>% filter(signif <= 2500 & difference >= enrich_cutoff) %>% ## signif is 95% CI with a specified cutoff
  filter(clust %in% filtered_class) %>% ## filter the cluster
  arrange(desc(difference)) %>% ## arrange enrichment score in descending order
  .[, "path"] %>% as.character() %>% unique() %>% .[1:n_path] ## getting the top10 enriched pathways

genes_in_path <- gene2level2_lookup %>% .[, match(pathname2level2$PATH_ID, names(.))] %>% ## match path ids
  'colnames<-' (pathname2level2$PATH_NAME) %>% ## replace with path_names
  dplyr::select(c(toppath)) %>% ## filter by top 10 pathways
  rownames_to_column(var = "ensembl_gene_id") %>% left_join(., gene_data[,c("ensembl_gene_id", "external_gene_name")], by = "ensembl_gene_id") %>% column_to_rownames(var = "external_gene_name") %>% dplyr::select(-ensembl_gene_id) %>% ## replace ensembl gene id with gene name
  .[rowSums(.[, -1])>0,]

df <- upset(genes_in_path, 
      sets = names(genes_in_path),
      mb.ratio = c(0.55, 0.45), 
      order.by = "freq", 
      point.size = 3.5,
      line.size = 2.0,
      mainbar.y.label = "Gene Intersection",
      sets.x.label = "Total Gene Per Pathway",
      text.scale = c(2.5, 2.4, 2, 2.1, 2.4, 1.5),
      number.angles = 0)

make_combinations <- function(x) {
  l <- length(x)
  mylist <- lapply(1:l, function(y) {
    combn(x, y, simplify = FALSE)
  })
  mylist
}

path_combo <- make_combinations(names(genes_in_path)) ## possible pathway combinations from 1 to 10

top10path <- genes_in_path %>% rowSums() %>% as.data.frame() %>% ## getting the sums of genes in pathway
  'colnames<-' ("sum_top10") %>% ## rename col
  rownames_to_column(var = "gene_name") ## make rownames a col

path_match_in_set <- list() ## making a list for matchings in sets

for(n in 1:10) {
  message(n)
  path_combo_set <- path_combo[[n]] ## selecting combination set (1 combo, 2 combo, 3 combo, etc)
  path_match_within_set <- list() ## making a list for matching within sets
  for(p in 1:length(path_combo_set)) {
    message(p)
    path_name <- path_combo_set[[p]] ## selecting specific combination pathway names
    spec_combo <- genes_in_path %>% dplyr::select(all_of(path_name)) ## select pathway combo
    if(length(spec_combo) > 1) {
      spec_combo <- spec_combo %>% rowSums() %>% as.data.frame() %>% ## rowSums the pathway to get the gene total membership
        'colnames<-' ("combo") %>% filter(combo == n) ## rename col and filter for combo that is n (n combo)
    }
    if(length(spec_combo) == 1) {
      names(spec_combo) <- "combo"
    }
    spec_combo <- spec_combo %>% rownames_to_column(var = "gene_name") %>% left_join(., top10path, by = "gene_name")
    spec_combo$match <- spec_combo$combo == spec_combo$sum_top10
    any_matches <- as.character(unique(spec_combo$match)) ## are there any matches?
    if(!"TRUE" %in% any_matches) { ## if no matches then skip
      next
      }
    if("TRUE" %in% any_matches) { ## if are matches then do this
      path_match_within_set[[p]] <- spec_combo %>% filter(match == "TRUE") %>% dplyr::select(gene_name) %>% ## filter for trues and select only gene names
        mutate(path_combo = paste0(paste(path_name, collapse=", "))) ## insert combo type
    }
  }    
  if(length(path_match_within_set) > 0) {
    path_match_in_set[[n]] <- path_match_within_set %>% do.call(rbind, .) %>% as.data.frame()
  }
}
path_match_in_set <- path_match_in_set %>% do.call(rbind, .) %>% as.data.frame() ## combine the list together

save(path_match_in_set, file = "path_match_in_set.Rda")
load("../data/path_match_in_set.Rda")

### getting clustering order from pheatmap
most_genes <- path_match_in_set %>% .$path_combo %>% table() %>% as.data.frame() %>% arrange(desc(Freq)) %>% ## arranging pathway combination based on most genes involved
  'colnames<-' (c("path_combo", "Freq")) %>% dplyr::select(path_combo) %>%
  rownames_to_column(var = "order") 

gene_order <- path_match_in_set %>% left_join(., most_genes, by = "path_combo") %>% ## left join the data together
  arrange(order) %>% .$gene_name ## getting the gene name order


## now need to get the gene mutation data and tumor samples 
load("../data/gdc_tumor_coding_complete.Rdata")

## Booleanize mutation count for each tumor sample
missense <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$missense) 
splice <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$splice)
frameshdel <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$frameshdel)
frameshins <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$frameshins)
utr3 <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$utr3)
utr5 <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$utr5)
nonstop <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$nonstop)
nonsense <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$nonsense)

gdc_mut_count_patient <- missense + splice + frameshdel + frameshins + utr3 + utr5 + nonstop + nonsense ## add up all the mutation count
rm(missense, splice, frameshdel, frameshins, utr3, utr5, nonstop, nonsense, gdc_tumor_coding_complete)
gc()
gdc_mut_count_patient[gdc_mut_count_patient > 0] <- 1 ## booleanize data, anything greater than 1 is equal to 1

filtered_mut_data <- gdc_mut_count_patient %>% rownames_to_column(var = "ensembl_gene_id") %>% ## ensembl id to col
  left_join(., gene_data[,c("ensembl_gene_id", "external_gene_name")], by = "ensembl_gene_id") %>% ## left_join data by ensembl_gene_id
  column_to_rownames(var = "external_gene_name") %>% dplyr::select(-ensembl_gene_id) %>% ## replace ensembl_id with gene_name
  .[rownames(.) %in% gene_order, names(.) %in% class_spec] ## filter by genes in top10 path of filtered class and tumor samples associated with it
rm(gdc_mut_count_patient)
gc()

save(filtered_mut_data, gene_order, file = "filtered_mut_data.Rda")

fig4_pheatmap <- pheatmap(filtered_mut_data[gene_order,],
         show_rownames = T,
         show_colnames = F,
         treeheight_row = 0,
         treeheight_col = 0,
         cellheight = 5,
         cellwidth = 1,
         cluster_cols = T,
         cluster_rows = F, ## turn off row clustering
         annotation_legend = F,
         legend_breaks = c(0, 0.25, 0.75, 1),
         legend_labels = c("","Not Mut", "Mut", ""),
         color = c("grey", "firebrick3"),
         clustering_method = "ward.D2",
         fontsize = 10,
         legend = T)

## getting sample orders
pheatmap_order <- fig4_pheatmap$tree_col$order ## getting sample clustering order
sample_order <- names(filtered_mut_data) ## getting the sample_id original order 
sample_order <- sample_order[pheatmap_order] ## reorder cancer by heatmap order

## stopped here ## ignore bottom using as reference

class67_gene_2_path_heatmap <- filtered_mut_data %>% rownames_to_column(var = "gene_name") %>%  ## move rownames to column
  gather(., key = "sample_id", value = "membership", -gene_name) ## wide to long format
class67_gene_2_path_heatmap$membership <- as.character(class67_gene_2_path_heatmap$membership) ## turn boolean values into categories

## set levels based on clustering algorithm above
class67_gene_2_path_heatmap$gene_name <- factor(class67_gene_2_path_heatmap$gene_name, levels = c(rev(rownames(filtered_mut_data))))
class67_gene_2_path_heatmap$sample_id <- factor(class67_gene_2_path_heatmap$sample_id, levels = c(sample_order))

class67_gene_2_path_heatmap <- left_join(class67_gene_2_path_heatmap, path_match_in_set, by = "gene_name") ## add in path_combo for faceting 
save(class67_gene_2_path_heatmap, file = "class67_gene_2_path_heatmap.Rda") 
rm(list = ls(all.names = T))
gc()
```

```{r child = '../code/figure4_function.Rmd'}
```


```{r figure-4-oncoprint, message = FALSE, fig.cap="**Figure 4: Some genes with multiple pathway memberships drive clustering.** Each column is a tumor in class 6 or 7, each row represents a gene with mutation (red) or not mutated (grey). The genes are organized according to which of the top distinguishing pathways for this class that they effect. Some genes affect multiple pathways, as indicated by the bars at left. The highlighted genes at right are all proteasomal subunits."}

fig4 <- oncoprint_style(filtered_class = c(6,7), n_path = 10)
fig4

```


```{r figure-4, message = FALSE, fig.cap="**Figure 4: Some genes with multiple pathway memberships drive clustering.** Each column is a tumor in class 6 or 7, each row represents a gene with mutation (red) or not mutated (grey). The genes are organized according to which of the top distinguishing pathways for this class that they effect. Some genes affect multiple pathways, as indicated by the bars at left. The highlighted genes at right are all proteasomal subunits.", eval = FALSE}
load("../data/class67_gene_2_path_heatmap.Rda") ## load data
load("../data/path_match_in_set.Rda")

### getting facet ordering
most_genes <- path_match_in_set %>% .$path_combo %>% table() %>% as.data.frame() %>% arrange(desc(Freq)) %>% ## arranging pathway combination based on most genes involved
  'colnames<-' (c("path_combo", "Freq")) %>% 
  rownames_to_column(var = "order") 

gene_order <- path_match_in_set %>% left_join(., most_genes, by = "path_combo") %>% ## left join the data together
  arrange(order) %>% .$gene_name ## getting the gene name order

class67_gene_2_path_heatmap$gene_name <- factor(class67_gene_2_path_heatmap$gene_name, levels = c(rev(gene_order)))

fig4 <- ggplot(data = class67_gene_2_path_heatmap, aes(y=gene_name, x=sample_id, fill = membership)) + 
  geom_tile(size = 0.6) +
  scale_fill_manual(values = c("grey", "firebrick3")) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_blank(),
        axis.ticks = element_blank(),
        strip.text.y = element_blank(),
        strip.background = element_blank(),
        legend.position = "none") 

load("../data/path_match_in_set.Rda")

gene_order <- path_match_in_set %>% left_join(., most_genes, by = "path_combo") %>% ## left join the data together
  arrange(order) %>% .$gene_name ## getting the gene name order

## right annotation data generation
proteasome_r_anno <- data.frame(gene = gene_order, 
                                psm_gene = 0)

proteasome_r_anno[grep(pattern = "PSM|UBE2|UBB|UBC", x = proteasome_r_anno$gene), "psm_gene"] <- 1

r_anno_color <- c("0" = "white", "1" = "black")
r_anno <- ggplot(proteasome_r_anno) +
  geom_bar(mapping = aes(x = 1, y = gene, fill = as.character(psm_gene)), 
           stat = "identity", 
           width = 1) +
  scale_fill_manual(values = r_anno_color, breaks = "1", name = "", labels = "PSM Gene") +
  theme_void() 
legend <- plot_grid(get_legend(r_anno), ncol = 1)
r_anno <- r_anno + theme(legend.position = "none")

## left annotatoin data generation
l_anno <- path_match_in_set %>% .[match(gene_order, .$gene_name),] ## order by the gene order from the heatmap

## need to get top path names again
load("../data/moderate_enrich_prob.Rda")
enrich_cutoff <- 0.30
filtered_class <- c(6,7)
n_path <- 10
toppath <- moderate_enrich_prob %>% filter(signif <= 2500 & difference >= enrich_cutoff) %>% ## signif is 95% CI with a specified cutoff
  filter(clust %in% filtered_class) %>% ## filter the cluster
  arrange(desc(difference)) %>% ## arrange enrichment score in descending order
  .[, "path"] %>% as.character() %>% unique() %>% .[1:n_path] ## getting the top10 enriched pathways

for(p in toppath){
  message(p)
  l_anno <- l_anno %>% mutate(p = 0) ## create a new col named p
  names(l_anno)[names(l_anno) == 'p'] <- p ## rename col with pathway name
  ## for any path_combo that includes the pathway name change the 0 into a 1
  if(p == "AUF1 (hnRNP D0) binds and destabilizes mRNA") { ## if it has this pathway grep a different way
    l_anno[grep(pattern = "AUF1", x = l_anno$path_combo), p] <- 1
  }
  if(p != "AUF1 (hnRNP D0) binds and destabilizes mRNA") { ## if it is not AUF1 do it normally
  l_anno[grep(pattern = p, x = l_anno$path_combo), p] <- 1 
  }
}

l_anno_ggplot <- list() ## list for storing ggplots
path_legend <- list()

kelly.colours <- c("gray95", "gray13", "gold2", "plum4", "darkorange1",
                   "lightskyblue2", "firebrick", "burlywood3", "gray51", "springgreen4",
                   "lightpink2", "deepskyblue4", "lightsalmon2", "mediumpurple4",
                   "orange", "maroon", "yellow3", "brown4", "yellow4", "sienna4", "chocolate", "gray19")

for(n in 1:length(toppath)){
  message(n)
  p <- toppath[n]
  message(p)
  spec_path <- l_anno[,c("gene_name", p)]
  names(spec_path)[names(spec_path) == p] <- "p"
  anno_color <- c("0" = "white", "1" = kelly.colours[2+n])
  path_ggplot <- ggplot(spec_path) +
  geom_bar(mapping = aes(x = 1, y = gene_name, fill = as.character(p)), 
           stat = "identity", 
           width = 1) +
  scale_fill_manual(values = anno_color, breaks = "1", name = "", labels = p) +
  theme_void() 
  path_legend[[n]] <- plot_grid(get_legend(path_ggplot), ncol = 1) ## extract legend from plot
  l_anno_ggplot[[n]] <- path_ggplot + theme(legend.position = "none") ## remove legend from plot
}


plot <- plot_grid(l_anno_ggplot[[1]], l_anno_ggplot[[2]], l_anno_ggplot[[3]], l_anno_ggplot[[4]], l_anno_ggplot[[5]], l_anno_ggplot[[6]], l_anno_ggplot[[7]], l_anno_ggplot[[8]], l_anno_ggplot[[9]], l_anno_ggplot[[10]], fig4, r_anno, align = "h", ncol = 12, axis = "tb", rel_widths = c(rep(0.1, 10), 15, 0.1))
plot_legend <- plot_grid(path_legend[[1]], path_legend[[2]], path_legend[[3]], path_legend[[4]], path_legend[[5]], path_legend[[6]], path_legend[[7]], path_legend[[8]], path_legend[[9]], path_legend[[10]], ncol = 5)

plot_grid(plot, plot_legend, ncol = 1, rel_heights = c(10, 1.5))

```