```{r group-pathway-enrichment-data-generation, eval=FALSE}
tumor_clusters <- fread("../data/umap_2d_3d_coors.tsv") ## load in data
tumor_clusters <- tumor_clusters %>% as.data.frame() %>% dplyr::select(V1, knn_clust) ## select the relevant columns

## Getting the total number of tumor samples in each cluster
n_tumor_in_clust <- as.data.frame(table(tumor_clusters$knn_clust)) %>% ## table the number of tumors in each cluster
  'colnames<-' (c("clust", "tot_n_clust")) %>% ## move cluster number to rownames
  mutate(clust = as.character(clust)) ## convert factor to character


## Organizing rBeta data
load("../data/gdc_reactome_path_analysis.Rda")
clust_group <- n_tumor_in_clust$clust
cluster_path_count <- list()
for(n in clust_group) {
  print(n)
  sample_id <- tumor_clusters %>% filter(knn_clust == n) %>% ## filter for tumor class
    .[,"V1"] ## get sample_ids
  path_mutation <- gdc_reactome_path_analysis %>% .[,names(.) %in% sample_id] %>% ## getting the tumor samples from path analysis
    rowSums() %>% as.data.frame() %>% ## getting the observed mutation count of tumor class
    'colnames<-' (n) ## change colname to cluster number
  cluster_path_count[[n]] <- path_mutation
  rm(path_mutation, sample_id, n)
  gc()
}
cluster_path_count <- do.call(cbind, cluster_path_count) ## Combine the list together

global_path_mut <- cluster_path_count %>% rowSums() %>% as.data.frame() %>% ## global pathway mutation count
  .[rep(1:ncol(.), each = 12)] %>% ## replicate the column 12 times for the 12 tumor classes
  'colnames<-' (clust_group) %>% ## rename column with tumor class
  rownames_to_column(var = "path") %>% ## move rownames to column (pathways) %>%
  gather(., key = "clust", value = "global_mut", -path)

rbeta_path_analysis <- cluster_path_count %>% rownames_to_column(var="path") %>%
  gather(key = "clust", value = "clust_mut", -path) %>% ## Wide to long format
  left_join(., global_path_mut, by = c("path", "clust")) %>% ## add global mutation count 
  left_join(., n_tumor_in_clust, by = "clust") %>% ## add total number of tumor samples per clust 
  mutate(global_sample = sum(n_tumor_in_clust$tot_n_clust)) ## add total number of tumor samples

rm(global_path_mut, cluster_path_count, n_tumor_in_clust, clust_group, tumor_clusters, gdc_reactome_path_analysis)
gc()

enrich_prob_uncertainity_in_bg <- data.frame(path = rbeta_path_analysis$path,
                                            clust = rbeta_path_analysis$clust,
                                            fg_mut = rbeta_path_analysis$clust_mut,
                                            fg_not_mut = rbeta_path_analysis$tot_n_clust - rbeta_path_analysis$clust_mut,
                                            bg_mut = rbeta_path_analysis$global_mut,
                                            bg_not_mut = rbeta_path_analysis$global_sample - rbeta_path_analysis$global_mut
                                            )
fg_mut_rate <- list()
bg_mut_rate <- list()
for(n in 1:max(as.numeric(unique(enrich_prob_uncertainity_in_bg$clust)))) {
  print(n)
  df <- subset(enrich_prob_uncertainity_in_bg, clust == n)
  fg_denominator <- nrow(df) * (df$fg_mut[1] + df$fg_not_mut[1]) ## n_path * tot_n_clust_x
  fg_numerator <- sum(df$fg_mut)
  bg_denominator <- nrow(df) * (df$bg_mut[1] + df$bg_not_mut[1])
  bg_numerator <- sum(df$bg_mut)
  fg_mut_rate[[n]] <- fg_numerator / fg_denominator
  bg_mut_rate[[n]] <- bg_numerator / bg_denominator
  rm(df)
}

fg_mut_rate <- fg_mut_rate %>% do.call(rbind, .) %>% as.data.frame() %>% ## rbind the mut rates from list
  'colnames<-' ("fg_mut_rate") %>% ## rebind col names
  rownames_to_column(var = "clust") ## move rownames to col
bg_mut_rate <- bg_mut_rate %>% do.call(rbind, .) %>% as.data.frame() %>% ## rbind the mut rates from list
  'colnames<-' ("bg_mut_rate") %>% ## rebind col names
  rownames_to_column(var = "clust") ## move rownames to col

enrich_prob_uncertainity_in_bg <- enrich_prob_uncertainity_in_bg %>% left_join(., fg_mut_rate, by = "clust") %>%
  left_join(., bg_mut_rate, by = "clust") %>%
  mutate(rel_odds = .$fg_mut_rate / .$bg_mut_rate) %>%
  mutate(denominator = (.$bg_mut * .$rel_odds) + (.$bg_not_mut / .$rel_odds)) %>%
  mutate(x_adj =(.$fg_mut + .$fg_not_mut) * (.$bg_mut * .$rel_odds) / .$denominator) %>%
  mutate(y_adj = (.$fg_mut + .$fg_not_mut) - .$x_adj)
rm(fg_mut_rate, bg_mut_rate, rbeta_path_analysis)
gc()

moderate_fg <- apply(enrich_prob_uncertainity_in_bg[,c("fg_mut", "fg_not_mut")], MARGIN = 1, function(x) {
  rbeta(n = 1e5, shape1=x["fg_mut"], shape2=x["fg_not_mut"])
})

moderate_bg <- apply(enrich_prob_uncertainity_in_bg[,c("x_adj", "y_adj")], MARGIN = 1, function(x) {
  rbeta(n = 1e5, shape1=x["x_adj"], shape2=x["y_adj"])
})

## ModerateEnrichment probability 
prob <- moderate_fg > moderate_bg ## boolean data
mean_prob <- apply(prob, MARGIN = 2, function(x) {
  mean(x)
})
rm(prob)
gc()
## Moderate Difference
CI <- 0.025 ## setting a 95% confidence interval

diff_fg_bg <- moderate_fg - moderate_bg ## fg - bg
rm(moderate_fg, moderate_bg, prob)
gc()

sig_fg_bg <- as.data.frame(apply(diff_fg_bg, MARGIN = 2, function(x) {
  sum(x < 0 ) ## out of 1e5 simulations, how many times is fg-bg less than 0
}))
quant_diff <- t(apply(diff_fg_bg, MARGIN = 2, function(x) {
  quantile(x, c(CI, 0.5, 1-CI))
}))

moderate_enrich_prob <- data.frame(path = enrich_prob_uncertainity_in_bg$path,
                                   clust = enrich_prob_uncertainity_in_bg$clust,
                                   probability = mean_prob,
                                   signif = sig_fg_bg[,1],
                                   difference = quant_diff[,2],
                                   lower = quant_diff[,1],
                                   upper = quant_diff[,3])
rm(enrich_prob_uncertainity_in_bg, mean_prob, quant_diff, sig_fg_bg, diff_fg_bg)
gc()
#save(moderate_enrich_prob, file = "moderate_enrich_prob.Rda")
load("../data/moderate_enrich_prob.Rda")

diff_heatmap <- moderate_enrich_prob[,c("path", "clust", "difference")]
diff_heatmap <- spread(diff_heatmap, key = "clust", value = "difference")
diff_heatmap <- diff_heatmap %>% remove_rownames() %>% column_to_rownames(var="path")

effect_size <- pheatmap(diff_heatmap,
         show_rownames = F,
         show_colnames = T,
         cluster_cols = T,
         cluster_rows = T,
         cellwidth = 10,
         cellheight = 0.76,
         color = rev(c('#7f3b08','#b35806','#e08214','#fdb863','#fee0b6','white', '#d8daeb','#b2abd2','#8073ac','#542788','#2d004b')),
         breaks = c(seq(from = -1, -0.2, 0.2), -0.0001, 0.0001, seq(from = 0.2, to = 1, by = 0.2)),
         clustering_method = "ward.D2")

effect_row_order <- effect_size$tree_row$order
effect_row_order <- diff_heatmap %>% .[effect_row_order,] %>% rownames() ## getting row order of pheatmap

effect_heatmap <- diff_heatmap %>% rownames_to_column(var = "path_name") %>% 
  gather(., key = "cluster", value = "effect_size", -path_name) 

effect_heatmap$path_name <- factor(effect_heatmap$path_name, levels = c(rev(effect_row_order)))
effect_heatmap$cluster <- factor(effect_heatmap$cluster, levels = c(1:12))
effect_segments <- c(seq(from = -1, -0.2, 0.2), -0.0001, 0.0001, seq(from = 0.2, to = 1, by = 0.2))

effect_heatmap <- effect_heatmap %>% mutate(discrete_color = case_when(
  effect_size > effect_segments[1] & effect_size <= effect_segments[2] ~ "1",
  effect_size > effect_segments[2] & effect_size <= effect_segments[3] ~ "2",
  effect_size > effect_segments[3] & effect_size <= effect_segments[4] ~ "3",
  effect_size > effect_segments[4] & effect_size <= effect_segments[5] ~ "4",
  effect_size > effect_segments[5] & effect_size <= effect_segments[6] ~ "5",
  effect_size > effect_segments[6] & effect_size <= effect_segments[7] ~ "6",
  effect_size > effect_segments[7] & effect_size <= effect_segments[8] ~ "7",
  effect_size > effect_segments[8] & effect_size <= effect_segments[9] ~ "8",
  effect_size > effect_segments[9] & effect_size <= effect_segments[10] ~ "9",
  effect_size > effect_segments[10] & effect_size <= effect_segments[11] ~ "10",
  effect_size > effect_segments[11] & effect_size <= effect_segments[12] ~ "11"
))
effect_heatmap$discrete_color <- factor(effect_heatmap$discrete_color, levels = c(1:11))

save(effect_heatmap, file = "effect_heatmap.Rda")
```

```{r group-pathway-enrichment heatmap, fig.cap="**Figure 3. Pathway-specific enrichment within clusters.** Heatmap shows relative enrichment of each pathway (rows) within each numbered cluster (columns). The annotation at left indicates the Reactome pathway group at the second level (check this)."}
load("../data/effect_heatmap.Rda") ## load data

effect_colors = c("1" = "#2d004b", "2" = "#542788", "3" = "#8073ac", "4" = "#b2abd2", "5" = "#d8daeb", "6" = "white", "7" = "#fee0b6", "8" = "#fdb863", "9" = "#e08214","10" = "#b35806","11" ="#7f3b08") ## color scheme

fig3 <- ggplot(data = effect_heatmap, aes(x=cluster, y=path_name)) + 
  geom_tile(size = 0.6, aes(fill = discrete_color)) +
  scale_fill_manual(values = effect_colors) +
  theme(axis.text.x = element_text(size = 12),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.ticks = element_blank(),
        legend.position = "none")

fig3_legend <- ggplot(data = data.frame(x = 1:11, y = 1), aes(x = x, y = y, fill = as.factor(x))) +
  geom_bar(stat = "identity", width = 1) +
  theme_classic() +
  scale_fill_manual(values = effect_colors) + 
  scale_x_continuous(labels= c("-1", "-0.5","0", "0.5", "1")) +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.line = element_blank())

## setting patchwork panel layout
layout <- '
AAAAA
AAAAA
AAAAA
AAAAA
AAAAA
AAAAA
AAAAA
AAAAA
#BBB#
'

fig3 + fig3_legend + plot_layout(design = layout)
```