<div style="text-align: right"> Table 1 Data </div>
```{r table-1-data-generation, eval = FALSE}
tumor_clusters <- fread("../data/umap_3d_coors.tsv") ## load in data
load("../data/moderate_enrich_prob.Rda") ## load data
load("../data/gene2_level2_lookup.Rda")
load("../data/gene_data.Rda")
load("../data/gdc_gene_exp_adj.Rda")
load("../data/pathname2level2.Rda")

id_to_names <- gene2level2_lookup %>% rownames_to_column(var = "ensembl_gene_id") %>% ## convert ensembl to gene name
  left_join(., gene_data[,c("ensembl_gene_id", "external_gene_name")], by = "ensembl_gene_id") %>%
  remove_rownames() %>% column_to_rownames(var = "external_gene_name") %>%
  dplyr::select(-ensembl_gene_id) %>%
  t() %>% as.data.frame() %>% rownames_to_column(var = "PATH_ID") %>% ## convert path_id to path_name
  left_join(., pathname2level2, by = "PATH_ID") %>%
  remove_rownames() %>% column_to_rownames(var = "PATH_NAME") %>%
  dplyr::select(-PATH_ID) %>%
  t() %>% as.data.frame()

gene_mutation <- gdc_gene_exp_adj %>% rownames_to_column(var = "ensembl_gene_id") %>% ## convert ensembl to gene name
  left_join(., gene_data[,c("ensembl_gene_id", "external_gene_name")], by = "ensembl_gene_id") %>%
  remove_rownames() %>% column_to_rownames(var = "external_gene_name") %>%
  dplyr::select(-ensembl_gene_id)

## parameters ##
enrich_cutoff <- 0.30
howmanypaths <- 5 ## top _ pathways; how many top pathways do you want to see
show_perc <- TRUE
show_n <- TRUE
mutated_gene_position <- 1
################

clust_spec_enrich <- moderate_enrich_prob %>% filter(signif <= 2500 & difference >= enrich_cutoff) ## signif is 95% CI with a specified cutoff

clust_spec_enrich_top5 <- list()
for(n in unique(clust_spec_enrich$clust)) {
  message(n)
  clust_spec_enrich_top5[[n]] <- clust_spec_enrich %>% filter(clust == n) %>% ## filter for specific cluster
    arrange(desc(difference)) %>% ## arrange enrichment score in decreasing order 
    dplyr::select(path, clust) %>% .[1:5,]
}
clust_spec_enrich_top5 <- clust_spec_enrich_top5 %>% do.call(rbind, .) %>% as.data.frame() ## combine list from for loop
rm(clust_spec_enrich)

## finding the top mutated gene for each cluster in each pathway for the top 5 pathways 
type <- unique(tumor_clusters$project_code) ## type of cancer type in data
cluster_spec_enrich_table <- list() ## list for forloop

for(d in unique(clust_spec_enrich_top5$clust)) {
  message(d)
  clust_toppath <- clust_spec_enrich_top5 %>% filter(clust == d) %>% .$path %>% as.character() ## get the top pathway names for spec class
  class_spec <- tumor_clusters %>% dplyr::select(sample_id, clust_knn, project_code) %>% filter(clust_knn %in% d) ## get the smaple ids and cancer type for spec class
  top_genes_in_path_cancer_type <- list()
  for(n in clust_toppath) { ## for each of the top paths do this
    message(n)
    gene_in_path <- id_to_names %>% .[,which(names(.) == n)] %>% as.data.frame() %>% ## select pathway
    'rownames<-' (rownames(id_to_names)) %>% 
    filter(. == 1) %>% ## filter for genes that are in that pathway
    rownames(.)
    top_gene_in_path <- list()
    for(t in type) { ## looping through cancer type within class
      message(t)
      class_spec <- tumor_clusters %>% dplyr::select(sample_id, clust_knn, project_code) %>% filter(clust_knn == d) ## sample_id for class
      if(t %in% class_spec$project_code) { ## if cancer type is in class then run this 
        class_type_spec <- class_spec %>% filter(project_code == t) %>% column_to_rownames(var = "sample_id") %>% rownames() ## get cancer type specific tumor classes
      if(length(class_type_spec) == 1) { ## if you only have 1 sample_id in the class
        top_mut_gene <- gene_mutation %>% rownames_to_column(var = "gene") %>% .[.$gene %in% gene_in_path, names(.) %in% c("gene",  class_type_spec)] %>% remove_rownames() %>% column_to_rownames(var = "gene") %>% 'colnames<-' ("obs_count") %>%
          rownames_to_column(var = "gene") %>%
          mutate(n_sample = length(class_type_spec),
               perc_mut = round((obs_count / length(class_type_spec)) * 100, digits = 1)) %>% 
         arrange(desc(obs_count))
      }
      if(length(class_type_spec) > 1) { ## if you have more than 1 sample_id in the class
        top_mut_gene <- gene_mutation %>% .[rownames(.) %in% gene_in_path, names(.) %in% class_type_spec] %>% 
        rowSums() %>% as.data.frame() %>% 'colnames<-' ("obs_count") %>%
        rownames_to_column(var = "gene") %>%
        mutate(n_sample = length(class_type_spec),
               perc_mut = round((obs_count / length(class_type_spec)) * 100, digits = 1)) %>% 
         arrange(desc(obs_count))
      }
      if(show_perc == TRUE & show_n == FALSE) {
         top_gene_in_path[[t]] <- paste0(top_mut_gene$gene[mutated_gene_position], " (", top_mut_gene$perc_mut[mutated_gene_position],"%)")  
      }
      if(show_perc == TRUE & show_n == TRUE) {
         top_gene_in_path[[t]] <- paste0(top_mut_gene$gene[mutated_gene_position], " (", top_mut_gene$perc_mut[mutated_gene_position],"%)", "    n = ", length(class_type_spec))  
      }
      if(show_perc == FALSE) {
         top_gene_in_path[[t]] <- paste0(top_mut_gene$gene[mutated_gene_position])  
      }
      }
      if(!(t %in% class_spec$project_code)){ ## if cancer type is not in class then insert NA
        top_gene_in_path[[t]] <- "NA" 
      }
    }
    top_gene_in_path <- top_gene_in_path %>% do.call(rbind, .) %>% as.data.frame() %>% 'colnames<-' (n)
    clust_row <- data.frame(Class = d, row.names = n) %>% t() ## creating a row for cluster membership
    top_genes_in_path_cancer_type[[n]] <- rbind(clust_row, top_gene_in_path)
  }
  cluster_spec_enrich_table[[n]] <- top_genes_in_path_cancer_type %>% do.call(cbind, .) %>% as.data.frame() %>% 
  t() %>% as.data.frame() %>% rownames_to_column(var = "Pathway")
  }

cluster_spec_enrich_table <- cluster_spec_enrich_table %>% do.call(rbind, .) %>% as.data.frame()
save(cluster_spec_enrich_table, file = "../data/cluster_spec_enrich_table.Rda")
rm(list = ls(all.names = T))
gc()
```

```{r table-1}
load("../data/cluster_spec_enrich_table.Rda")
tumor_clusters <- fread("../data/umap_3d_coors.tsv") ## load in data

## Selecting the top 10 cancers with the largest n for table 1
n_tumor <- as.data.frame(table(tumor_clusters$project_code))
n_tumor <- n_tumor %>% arrange(desc(Freq)) %>% .[1:10, "Var1"] %>% as.character() %>% .[order(.)]

cluster_spec_enrich_table %>% .[, c("Pathway", "Class", n_tumor)] %>% kable(caption = "Table 1: Most mutated gene in class-specific pathways (enrichment score >= 0.30) for specific cancer", row.names = FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE, font_size = 12) %>%
  column_spec(1, bold = T)
```
<p style="FONT-SIZE:10px; COLOR:#000000; LINE-HEIGHT:12px;">**Table 1:** The numbers in this table are completely wrong, it is just a place holder, please ignore</p>
