<div style="text-align: right"> Supplementary Figure S4 Data </div>
```{r supplementary-figure-s4-data-generation, eval = FALSE}
load("../data/gdc_reactome_path_analysis.Rda") ## load data
umap_cancertype <- fread("../data/umap_2d_3d_coors.tsv") 
n_path <- 377 ## how many pathways do we want to look at starting from the most to least mutated pathway

toppath <- gdc_reactome_path_analysis %>% rowSums() %>% as.data.frame() %>% rownames_to_column(var = "path_name") %>% arrange(desc(.)) %>% .[1:n_path,] %>% .[, "path_name"] ## order pathway by most to least mutated pathway

selected_path <- gdc_reactome_path_analysis %>% t() %>% as.data.frame() %>% rownames_to_column(var = "V1") ## prepare pathway for left_join

selected_path <- umap_cancertype %>% dplyr::select(V1, x_2d, y_2d) %>% ## select relevant columns
  left_join(., selected_path, by = "V1") %>%
  melt(data = ., id.vars = c("V1", "x_2d", "y_2d")) %>%
  filter(value != 0)

save(selected_path, file = "selected_path.Rda")
```

```{r supplementary-figure-s4, out.width = '90%'}
load("../data/selected_path.Rda") ## load data
load("../data/gdc_reactome_path_analysis.Rda")
umap_cancertype <- fread("../data/umap_2d_3d_coors.tsv")
umap_bg <- umap_cancertype[,-"project_code"] ## get background data for facet

n_path <- 377 ## number of pathways we want to see

toppath <- gdc_reactome_path_analysis %>% rowSums() %>% as.data.frame() %>% rownames_to_column(var = "path_name") %>% arrange(desc(.)) %>% .[1:n_path,] %>% .[, "path_name"] ## order pathway by most to least mutated pathway.. needed for facet

ggplot(selected_path, aes(x = x_2d, y = y_2d, colour = as.character(value))) + 
  geom_point(data = umap_bg, aes(x = x_2d, y = y_2d), colour = "grey", size = 0.5) +
  geom_point(size = 0.5) +
  theme_classic() +
  coord_fixed() +
  xlab("UMAP 1") + ylab("UMAP 2") +
  scale_colour_manual(values = rep("firebrick3", 20)) +
  theme(axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    axis.line = element_blank(),
    legend.position = "none") +
  facet_wrap(~ factor(variable, levels = toppath),
                      ncol = 5) ## facet by pathways

```