<div style="text-align: right"> Supplementary Figure S3 Data </div>
```{r supplementary-figure-s3-data-generation, eval = FALSE}
load("../data/gdc_tumor_coding_complete.Rdata")
load("../data/gene_data.Rda")

## Booleanize mutation count for each tumor sample
missense <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$missense) 
splice <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$splice)
frameshdel <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$frameshdel)
frameshins <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$frameshins)
utr3 <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$utr3)
utr5 <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$utr5)
nonstop <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$nonstop)
nonsense <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$nonsense)

gdc_mut_count_patient <- missense + splice + frameshdel + frameshins + utr3 + utr5 + nonstop + nonsense ## add up all the mutation count
rm(missense, splice, frameshdel, frameshins, utr3, utr5, nonstop, nonsense)
gc()
gdc_mut_count_patient[gdc_mut_count_patient > 0] <- 1 ## booleanize data, anything greater than 1 is equal to 1

##oncogene
oncogene <- c("AKT2","BCL2","CTNNB1","ERBB2","KRAS","MDM2","MYC","PIK3CA","TET2","USP6") ## list of selected oncogene
##tumor_supressor
tumor_suppressor <- c("APC","BRIP1","CDKN2C","CHEK2","MSH2","PTEN","RB1","SMARCA4","TP53","VHL") ## list of selected tumor suppressor

selected_mut <- gene_data %>% dplyr::select(external_gene_name, ensembl_gene_id) %>% filter(external_gene_name %in% c(oncogene, tumor_suppressor)) ## getting ensembl_id for the oncogenes for filtering gdc data

selected_mut <- gdc_mut_count_patient %>% filter(rownames(.) %in% selected_mut$ensembl_gene_id) %>% ## filter by ensembl ids
  rownames_to_column(var = "ensembl_gene_id") %>% left_join(., selected_mut, by = "ensembl_gene_id") %>% ## replace ensembl ids with gene name 
  column_to_rownames(var = "external_gene_name") %>% dplyr::select(-ensembl_gene_id) %>%
  t() %>% as.data.frame() %>% rownames_to_column(var = "V1")  ## prep for left_join


selected_mut <- umap_cancertype %>% dplyr::select(V1, x_2d, y_2d) %>% ## select relevant columns
  left_join(., selected_mut, by = "V1") %>%
  melt(data = ., id.vars = c("V1", "x_2d", "y_2d")) %>%
  filter(value != 0)

save(selected_mut, file = "selected_mut.Rda")
```

```{r supplementary-figure-s3}
load("../data/selected_mut.Rda")
umap_cancertype <- fread("../data/umap_2d_3d_coors.tsv") ## load data
umap_bg <- umap_cancertype[,-"project_code"] ## get background data for facet

ggplot(selected_mut, aes(x = x_2d, y = y_2d, colour = as.character(value))) + 
  geom_point(data = umap_bg, aes(x = x_2d, y = y_2d), colour = "grey", size = 0.5) +
  geom_point(size = 0.5) +
  theme_classic() +
  coord_fixed() +
  xlab("UMAP 1") + ylab("UMAP 2") +
  scale_colour_manual(values = rep("firebrick3", 20)) +
  theme(axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    axis.line = element_blank(),
    legend.position = "none") +
  facet_wrap(~ factor(variable, levels = c("AKT2","BCL2","CTNNB1","ERBB2","KRAS","MDM2","MYC","PIK3CA","TET2","USP6", 
                                           "APC","BRIP1","CDKN2C","CHEK2","MSH2","PTEN","RB1","SMARCA4","TP53","VHL")),
                      ncol = 5) ## facet by gene
```