<div style="text-align: right"> Figure 1 data </div>
```{r tumor-clusters, eval = FALSE}
####################
## Figure 1A data ##
####################
load("../data/gdc_reactome_path_analysis.Rda")
load("../data/gdc_tumor_coding_complete.Rdata")

path_daisy <- daisy(t(gdc_reactome_path_analysis), type = list(symm  = c(1:col(gdc_reactome_path_analysis))))
path_daisy <- as.dist(as.matrix(path_daisy))

path_daisy_row <- daisy(gdc_reactome_path_analysis, type = list(symm  = c(1:nrow(gdc_reactome_path_analysis))))
path_daisy_row <- as.dist(as.matrix(path_daisy_row))

pathway_dendro <- pheatmap(gdc_reactome_path_analysis,
         show_rownames = F,
         show_colnames = F,
         cellheight = 1,
         cellwidth = 0.5,
         clustering_distance_cols = path_daisy,
         clustering_distance_rows = path_daisy_row,
         cluster_cols = T,
         cluster_rows = T,
         cutree_cols = 19,
         annotation_legend = F,
         legend_breaks = c(0, 0.25, 0.75, 1),
         legend_labels = c("","Not Mut", "Mut", ""),
         color = c("grey", "firebrick3"),
         clustering_method = "ward.D2",
         legend = T)
dev.off()
pathway_dendro <- pathway_dendro$tree_row$order ## getting pathway row ordering
df <- rownames(gdc_reactome_path_analysis)
pathway_dendro <- df[pathway_dendro]

tumor_samples <- gdc_tumor_coding_complete %>% colData(.) %>%  ## get sample_id data from gdc
  as.data.frame(.) %>%
  dplyr::select(project_code, submitted_specimen_id) %>%  
  mutate(project_code = gsub(pattern = "\\-.*", replacement = "", x = .$project_code))

cancer_type <- tumor_samples %>% .$project_code %>% unique %>% .[order(.)] ## get unique cancer_type

cancer_dendro <- list() ## getting cancer type specific tumor sample clustering info

for(n in cancer_type) {
  cancer_info <- tumor_samples %>% rownames_to_column(var = "sample_id") %>% ## move sample_id to column
    filter(project_code == n) %>% ## filter for specific cancer type
    .[, "sample_id"] ## retain only sample_id
  cancer_path <- gdc_reactome_path_analysis %>% .[, names(.) %in% cancer_info] ## only including filtered sample_id
  cancer_heatmap <- pheatmap(cancer_path[pathway_dendro,], ## using pathway row order 
                          show_rownames = F,
                          show_colnames = F,
                          cellheight = 1,
                          cellwidth = 0.5,
                          cluster_cols = T,
                          cluster_rows = F,
                          annotation_legend = F,
                          color = c("grey", "firebrick3"),
                          clustering_method = "single", ## ordering is single linkage
                          legend = T)
  cancer_order <- cancer_heatmap$tree_col$order ## cancer order
  cancer_path <- names(cancer_path) ## getting the sample_id original order 
  cancer_dendro[[n]] <- cancer_path[cancer_order] ## reorder cancer by heatmap order
  rm(cancer_info, cancer_path)
  gc()
}
dev.off()

for(n in cancer_type[1]) { ## getting the order of clustering by cancer type by alphabetical order
  print(n)
  cancer_order <- as.data.frame(do.call(cbind, cancer_dendro[n])) ## read in first list
  names(cancer_order) <- "sample_id"
  cancer_order$type <- n
  for(p in cancer_type[-1]) {
    print(p)
    df1 <- as.data.frame(do.call(cbind, cancer_dendro[p])) ## read in rest of list in loop
    names(df1) <- "sample_id"
    df1$type <- p
    cancer_order <- rbind(cancer_order, df1) ## combine the two df and repeat the loop until end of cancer_type
    rm(df1)
    gc()
  }
}

cancer_dendro <- cancer_order %>% .[,"sample_id"] %>% as.character(.) ## sample_id ordering

cancer_disrupt_heatmap <- gdc_reactome_path_analysis %>% rownames_to_column(var = "path_name") %>%  ## move rownames to column
  gather(., key = "sample_id", value = "membership", -path_name) ## wide to long format
cancer_disrupt_heatmap$membership <- as.character(cancer_disrupt_heatmap$membership) ## turn boolean values into categories

## set levels based on clustering algorithm above
cancer_disrupt_heatmap$path_name <- factor(cancer_disrupt_heatmap$path_name, levels = c(rev(pathway_dendro)))
cancer_disrupt_heatmap$sample_id <- factor(cancer_disrupt_heatmap$sample_id, levels = c(cancer_dendro))

cancer_disrupt_heatmap <- left_join(cancer_disrupt_heatmap, cancer_order, by = "sample_id") ## add in cancer type information for faceting
save(cancer_disrupt_heatmap, file = "cancer_disrupt_heatmap.Rda") 

####################
## Figure 1C data ##
####################
gdc_path <- gdc_reactome_path_analysis %>% t() %>% as.data.frame() %>%
  rownames_to_column(var = "sample") %>% ## move path_names to column
  .[match(rownames(tumor_samples), .$sample),]
  
## umap analysis
set.seed(3296)
gdc.umap <- umap(gdc_path[,2:length(gdc_path)]) ## default n_component is 2
gdc_umap_coors <- data.frame(x_2d = gdc.umap$layout[,1], y_2d = gdc.umap$layout[,2])

####################
## Figure 1E data ##
####################
## To identify clusters using hdbscan, use umap in the third dimension
set.seed(3296)
gdc.umap.3d <- umap(gdc_path[,2:length(gdc_path)], n_components = 3)
gdc.umap.3d <- data.frame(x_3d = gdc.umap.3d$layout[,1], y_3d = gdc.umap.3d$layout[,2], z_3d = gdc.umap.3d$layout[,3]) ## coors of umap
rownames(gdc.umap.3d) <- gdc_path$sample ## insert sample_id in rownames
hdb_cluster_assignment <- hdbscan(gdc.umap.3d, minPts =  114) ## min group size for cluster is 114 (value before cluster number drops significantly)
umap_2d_3d_coors <- data.frame(x_2d = gdc_umap_coors$x_2d, y_2d = gdc_umap_coors$y_2d, x_3d = gdc.umap.3d$x_3d, y_3d = gdc.umap.3d$y_3d, z_3d = gdc.umap.3d$z_3d, clust = as.factor(hdb_cluster_assignment$cluster), member_prob = hdb_cluster_assignment$membership_prob, row.names = rownames(gdc.umap.3d)) ## clust 0 is unclassified cluster

####################
## Figure 1F data ##
####################
## reclassifying clust 0 using our classified cluster as training test and unclassified as test set
umap_2d_3d_coors$knn_clust <- umap_2d_3d_coors$clust
umap_2d_3d_coors$knn_clust[umap_2d_3d_coors$clust==0]<-class::knn(train = umap_2d_3d_coors[,c("x_3d", "y_3d", "z_3d")][which(umap_2d_3d_coors$clust!=0),],
                                                                  test = umap_2d_3d_coors[,c("x_3d", "y_3d", "z_3d")][which(umap_2d_3d_coors$clust==0),],
                                                                  cl = umap_2d_3d_coors$clust[umap_2d_3d_coors$clust!=0], 
                                                                  k=15)

####################
## Figure 1G data ##
####################
missense <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$missense) ## reading in mutation data from SE
splice <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$splice)
frameshdel <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$frameshdel)
frameshins <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$frameshins)
utr3 <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$utr3)
utr5 <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$utr5)
nonstop <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$nonstop)
nonsense <- as.data.frame(SummarizedExperiment::assays(gdc_tumor_coding_complete)$nonsense)

mutation_count <- missense + splice + frameshdel + frameshins + utr3 + utr5 + nonstop + nonsense ## add up all the mutation count
rm(missense, splice, frameshdel, frameshins, utr3, utr5, nonstop, nonsense)
gc()
mutation_count <-mutation_count %>% .[rownames(.) %in% rownames(gene2level2_lookup),] %>% ## filter data with genes in our pathway lookup table
  colSums() %>% as.data.frame() %>% ## sum the mutation count
  'colnames<-' (c("mut_count")) %>% ## rename colname
  rownames_to_column(var = "V1") ## move rownames to column

umap_2d_3d_coors <- left_join(umap_2d_3d_coors, mutation_count, by = "V1") 

####################
## Figure 1H data ##
####################
tumor_samples <- gdc_tumor_coding_complete %>% colData(.) %>% 
  as.data.frame(.) %>%
  dplyr::select(project_code) %>% 
  mutate(project_code = gsub(pattern = "\\-.*", replacement = "", x = .$project_code)) %>%
  rownames_to_column(var = "V1")

umap_2d_3d_coors <- left_join(umap_2d_3d_coors, tumor_samples, by = "V1")

####################
## Figure 1I data ##
####################
## getting subtype information on our cancer type
subtypes <- PanCancerAtlas_subtypes() 
tumor_subtypes <- substring(text = tumor_samples$submitted_specimen_id, first = 1, last = 12) ## sample_id for subsetting subtypes
subtypes <- subtypes %>% dplyr::select(pan.samplesID, Subtype_Selected) %>% ## select the relevant columns
  mutate(Subtype_Selected = gsub(pattern = ".*\\.", replacement = "", x = .$Subtype_Selected)) %>% ## remove the cancer acronym at the beginning
  mutate(pan.samplesID = substring(text = .$pan.samplesID, first = 1, last = 12)) %>% ## interested in 
  distinct() %>% ## only unique columns
  .[.$pan.samplesID %in% tumor_subtypes, ] %>% ## include sample_ids that are in our analysis
  filter(Subtype_Selected != "Normal") %>%
  .[!.$pan.samplesID %in% .[which(duplicated(.$pan.samplesID)),]$pan.samplesID, ] ## remove dups

#save(subtypes, file = "subtypes.Rda")
load("../data/subtypes.Rda")

umap_2d_3d_coors <- umap_2d_3d_coors %>%
  mutate(pan.samplesID = substring(text = .$V1, first = 1, last = 12)) %>%
  left_join(., subtypes, by = "pan.samplesID") %>% ## left_join subtype data to umap
  dplyr::select(-pan.samplesID)

##########################
## Figure 1K and L data ##
##########################
## getting tumor_metastasis, staging
tcga_clinical_tumor_staging <- list()
for(n in cancer_type) {
  print(n)
  cancername <- paste0("TCGA-",n)
  query <- GDCquery(project = cancername,
                  data.category = "Clinical",
                  data.type = "Clinical Supplement",
                  data.format = "BCR Biotab",
                  file.type = "patient")
  GDCdownload(query)
  clinical <- GDCprepare(query)[[1]]
  if("ajcc_pathologic_tumor_stage" %in% colnames(clinical) & "ajcc_tumor_pathologic_pt" %in% colnames(clinical) == T) {
    cat("Yep, ajcc info in there!\n")
    clinical <- clinical[-c(1:2), c("bcr_patient_barcode","ajcc_pathologic_tumor_stage", "ajcc_tumor_pathologic_pt", "ajcc_metastasis_pathologic_pm")]
  }
  if(!"ajcc_pathologic_tumor_stage" %in% colnames(clinical) & "clinical_stage" %in% colnames(clinical) & "ajcc_tumor_pathologic_pt" %in% colnames(clinical)== T) {
    cat("Nope, ajcc stage not there, but pathologic scores is!\n")
    clinical <- clinical[-c(1:2), c("bcr_patient_barcode", "clinical_stage", "ajcc_tumor_pathologic_pt", "ajcc_metastasis_pathologic_pm")]
    names(clinical) <- c("bcr_patient_barcode","ajcc_pathologic_tumor_stage", "ajcc_tumor_pathologic_pt", "ajcc_metastasis_pathologic_pm")
  }
  if(!"ajcc_pathologic_tumor_stage" %in% colnames(clinical) & "clinical_stage" %in% colnames(clinical) & !"ajcc_tumor_pathologic_pt" %in% colnames(clinical) & "pathologic_T" %in% colnames(clinical) == T) {
    cat("Nope, ajcc info not there!\n")
    clinical <- clinical[-c(1:2), c("bcr_patient_barcode", "clinical_stage", "pathologic_T", "pathologic_M")]
    names(clinical) <- c("bcr_patient_barcode","ajcc_pathologic_tumor_stage", "ajcc_tumor_pathologic_pt", "ajcc_metastasis_pathologic_pm")
    }
  if(!"ajcc_pathologic_tumor_stage" %in% colnames(clinical) & !"clinical_stage" %in% colnames(clinical) == T) next
  if("ajcc_pathologic_tumor_stage" %in% colnames(clinical) & !"ajcc_tumor_pathologic_pt" %in% colnames(clinical) == T) next
  tcga_clinical_tumor_staging[[n]] <- clinical
}

tcga_clinical_tumor_staging <- do.call(rbind, tcga_clinical_tumor_staging) ## rbind the list together
tcga_clinical_tumor_staging <- tcga_clinical_tumor_staging[tcga_clinical_tumor_staging$bcr_patient_barcode %in% tumor_subtypes,] ## We have 6633 out of 7607 tumor data
missing_sample <- as.data.frame(matrix(data = "NA", nrow = length(tumor_subtypes[!tumor_subtypes %in% tcga_clinical_tumor_staging$bcr_patient_barcode]), ncol = length(tcga_clinical_tumor_staging) -1 ))

tcga_clinical_tumor_staging <- missing_sample %>% 'colnames<-' (names(tcga_clinical_tumor_staging[-1])) %>% ## colnames based on tcga_clinical_tumor_staging
  mutate(bcr_patient_barcode = tumor_subtypes[!tumor_subtypes %in% tcga_clinical_tumor_staging$bcr_patient_barcode]) %>%
  .[,c(4,1,2,3)] %>% ## reorder columns for rbinding
  rbind(tcga_clinical_tumor_staging, .) ## rbind

save(tcga_clinical_tumor_staging, file = "tcga_clinical_tumor_staging.Rda")

umap_2d_3d_coors <- umap_2d_3d_coors %>%
  mutate(bcr_patient_barcode = substring(text = .$V1, first = 1, last = 12)) %>%
  left_join(., tcga_clinical_tumor_staging, by = "bcr_patient_barcode") %>% ## left_join clinical data to umap
  dplyr::select(-bcr_patient_barcode)

M0 <- umap_2d_3d_coors$ajcc_metastasis_pathologic_pm %in% c("cM0 (i+)", "M0")
M1 <- umap_2d_3d_coors$ajcc_metastasis_pathologic_pm %in% c("M1", "M1a", "M1b", "M1c")
NA.value <- umap_2d_3d_coors$ajcc_metastasis_pathologic_pm %in% c("[Discrepancy]", "[Not Applicable]", "[Not Available]", "MX")
  
umap_2d_3d_coors$ajcc_metastasis_pathologic_pm[M0] <- "M0"
umap_2d_3d_coors$ajcc_metastasis_pathologic_pm[M1] <- "M1"
umap_2d_3d_coors$ajcc_metastasis_pathologic_pm[NA.value] <- "NA"

stage1 <- umap_2d_3d_coors$ajcc_pathologic_tumor_stage %in% c("Stage I", "Stage IA", "Stage IA1", "Stage IA2", "Stage IB", "Stage IB1", "Stage IB2", "Stage IC")
stage2 <- umap_2d_3d_coors$ajcc_pathologic_tumor_stage %in% c("Stage II", "Stage IIA", "Stage IIA1", "Stage IIA2", "Stage IIB", "Stage IIC")
stage3 <- umap_2d_3d_coors$ajcc_pathologic_tumor_stage %in% c("Stage III", "Stage IIIA", "Stage IIIB", "Stage IIIC", "Stage IIIC1", "Stage IIIC2")
stage4 <- umap_2d_3d_coors$ajcc_pathologic_tumor_stage %in% c("Stage IV", "Stage IVA", "Stage IVB", "Stage IVC")
unknown <- umap_2d_3d_coors$ajcc_pathologic_tumor_stage %in% c("Stage X", "[Discrepancy]", "[Not Applicable]", "I/II NOS", "NA", "[Not Available]")

umap_2d_3d_coors$ajcc_pathologic_tumor_stage[stage1] <- "Stage I"
umap_2d_3d_coors$ajcc_pathologic_tumor_stage[stage2] <- "Stage II"
umap_2d_3d_coors$ajcc_pathologic_tumor_stage[stage3] <- "Stage III"
umap_2d_3d_coors$ajcc_pathologic_tumor_stage[stage4] <- "Stage IV"
umap_2d_3d_coors$ajcc_pathologic_tumor_stage[unknown] <- "Not Available"

write.table(x = umap_2d_3d_coors, file = "umap_2d_3d_coors.tsv", quote = FALSE, sep = "\t", row.names = FALSE) ## save the data
```

```{r fig-1a-1l, warning=FALSE, fig.height=11, fig.width=8.5, message = FALSE}
load("../data/cancer_disrupt_heatmap.Rda")
umap_cancertype <- fread("../data/umap_2d_3d_coors.tsv")

kelly.colours <- c("gray95", "gray13", "gold2", "plum4", "darkorange1",
                   "lightskyblue2", "firebrick", "burlywood3", "gray51", "springgreen4",
                   "lightpink2", "deepskyblue4", "lightsalmon2", "mediumpurple4",
                   "orange", "maroon", "yellow3", "brown4", "yellow4", "sienna4", "chocolate", "gray19")

fig1A <- ggplot(data = cancer_disrupt_heatmap, aes(y=sample_id, x=path_name, fill = membership)) + 
  geom_tile(size = 0.6) +
  scale_fill_manual(values = c("grey", "firebrick3")) +
  facet_grid(type ~ ., scales = "free", space = "free", switch = "y") +
scale_y_discrete(position = "left") +
  labs(tag = "A") +
  ylab("") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.ticks = element_blank(),
        strip.text.y = element_text(size = 12, hjust = 0),
        strip.text.y.left = element_text(angle = 0),
        strip.background = element_blank(),
        legend.position = "none") 

## fixing the text cutoff in heatmap
 fig1Ag <- ggplotGrob(fig1A)
 
 for(i in which(grepl("strip-l", fig1Ag$layout$name))){
   fig1Ag$grobs[[i]]$layout$clip <- "off"
 }
 
 fig1A <- as.ggplot(fig1Ag)
 rm(fig1Ag)

## umap monochrome 2d
fig1C <- ggplot(umap_cancertype, aes(x=x_2d, y=y_2d)) +
  geom_point(colour = "grey") +
  xlab("umap_1") +
  ylab("umap_2") +
  theme_classic() +
  labs(tag = "C") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.ticks = element_blank())
## umap hdb_scan
fig1E <- ggplot(subset(umap_cancertype, clust !=0), aes(x = x_2d, y = y_2d, color = as.factor(clust))) +
  geom_point(data = umap_cancertype, aes(x = x_2d, y = y_2d), colour = "grey") +
  geom_point() + scale_color_manual(values = kelly.colours[-c(1:2)]) +
  guides(color = F) +
  theme_classic() +
  xlab("umap_1") +
  ylab("umap_2") +
  theme_classic() +
  labs(tag = "E") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.ticks = element_blank())

## umap knn_clust 
fig1F <- ggplot(subset(umap_cancertype), aes(x = x_2d, y = y_2d, color = as.factor(knn_clust))) +
  geom_point() + scale_color_manual(values = kelly.colours[-c(1:2)]) +
  guides(color = F) +
  theme_classic() +
  xlab("umap_1") +
  ylab("umap_2") +
  theme_classic() +
  labs(tag = "F") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.ticks = element_blank())

umap_cancertype$knn_clust <- factor(umap_cancertype$knn_clust, levels = c(1:12))

## mutation burden plot
mut_order <- list() ## store data in list 
for(n in 1:max(as.numeric(as.character(umap_cancertype$knn_clust)))) { ## loop through all the clusters
  message(n)
  mut_order[[n]] <- umap_cancertype %>% filter(knn_clust == n) %>%  ## filter for specific class
    dplyr::select(V1, x_2d, y_2d, knn_clust, mut_count) %>% ## select relevant columns
    arrange(mut_count) ## arrange mutation in increasing order
}
mut_order <- mut_order %>% do.call(rbind, .) %>% as.data.frame() ## rbind list

mut_order$V1 <- factor(mut_order$V1, levels = mut_order$V1)
mut_order$knn_clust <- factor(mut_order$knn_clust, levels = c(1:12))

## Need the breaks positions for the x-axis
previous_class <- 0 ## starting position 1
position_of_previous_class <- 0 ## starting position 2
xaxis_breaks <- list() ## list for for loop
for(n in 1) { ## loop through 1 to 12 clusters
  message(n)
  class_spec <- round(mut_order %>% filter(knn_clust == n) %>% nrow(.) / 2, digits = 0) ## calculate halfway mark of class 
  xaxis_breaks[[n]] <- class_spec + previous_class + position_of_previous_class ## adding up all variables
  previous_class <- class_spec ## storing class halfway mark
  for(n in 2:max(as.numeric(as.character(mut_order$knn_clust)))) {
    message(n)
    position_of_previous_class <- xaxis_breaks[[n-1]] ## getting the previous class position
    class_spec <- round(mut_order %>% filter(knn_clust == n) %>% nrow(.) / 2, digits = 0) ## calculate halfway mark of new class
    xaxis_breaks[[n]] <- class_spec + previous_class + position_of_previous_class ## adding up all variables
    previous_class <- class_spec ## storing class halfway mark
  }
}
xaxis_breaks <- as.data.frame(do.call(rbind, xaxis_breaks)) ## rbind list
xaxis_breaks <- mut_order[rownames(mut_order) %in% xaxis_breaks$V1,] ## find the tumor samples in these positions

total_n <- as.data.frame(table(mut_order$knn_clust)) ## getting total n in cluster

mut_order$log10mut <- log10(mut_order$mut_count + 1) ## mutation count log transformation + pseudo count

mut_median <- mut_order %>% 
  group_by(knn_clust) %>% 
  dplyr::summarize(mut_med = median(log10mut)) ## calculate median for each class

fig1G <- ggplot(mut_order, aes(x = V1, y = log10mut, color = knn_clust)) + 
  geom_point() + 
  ylab("Log10(Mutation Count)") + 
  xlab("") +
  theme_classic() +
  facet_wrap(~ factor(knn_clust, levels = c(1:12)), ncol = 12, scales = "free_x") +
  geom_hline(data= mut_median, aes(yintercept=mut_med)) +
  scale_y_continuous(sec.axis = sec_axis(~.)) + ## dup y-axis
  scale_x_discrete(breaks = c(as.character(mut_order$V1[300]), as.character(xaxis_breaks$V1)), labels = c("n =" ,total_n$Freq)) +
  theme(axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.ticks.x = element_blank(),
        axis.line.x = element_line(colour = "black", size = 0.5),
        axis.line.x.top = element_line(colour = "black", size = 0.5),
        #strip.background.x = element_blank(),
        strip.placement = "outside",
        strip.text.x = element_text(size = 12),
        legend.position = "none") +
  scale_color_manual(values = kelly.colours[-c(1:2)])

## code to keep only the bottom border line of the facet
fig1G <- ggplotGrob(fig1G)
lg <- linesGrob(x=unit(c(0,1),"npc"), y=unit(c(0,0),"npc"), 
                   gp=gpar(col="black", lwd=4))

for (k in grep("strip-t",fig1G$layout$name)) {
  fig1G$grobs[[k]]$grobs[[1]]$children[[1]] <- lg
}

fig1G <- as.ggplot(fig1G)

## umap by cancer type
fig1H <- ggplot(umap_cancertype[umap_cancertype$project_code %in% c("COAD", "BRCA", "HNSC", "PAAD"),], aes(x = x_2d, y = y_2d, colour = project_code)) +
  geom_point(data = umap_cancertype, aes(x = x_2d, y = y_2d), colour = "grey") +
  geom_point() + 
  theme_classic() +
  ylab("umap_2") +
  xlab("umap_1") +
  labs(tag = "H", color = "") +
  scale_color_manual(labels = c("BRCA", "COAD", "HNSC", "PAAD"), 
                     values = c('#fb9a99', '#b15928', '#6a3d9a', 'springgreen4')) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.ticks = element_blank(),
        legend.position = "bottom")

## umap of brca subtype
fig1I <- ggplot(umap_cancertype %>% filter(project_code == "BRCA" & !is.na(Subtype_Selected)), aes(x = x_2d, y = y_2d, colour = Subtype_Selected)) +
  geom_point(data = umap_cancertype, aes(x = x_2d, y = y_2d), colour = "grey") +
  geom_point() +
  theme_classic() +
  ylab("umap_2") +
  xlab("umap_1") +
  labs(tag = "I", color = "") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.ticks = element_blank(),
        legend.position = "bottom")

## umap brca somatic mutations
load("../data/gdc_gene_exp_adj.Rda")
load("../data/gene_data.Rda")
umap_cancertype <- fread("../data/umap_2d_3d_coors.tsv")
brca <- gene_data %>% .[.$external_gene_name %in% c("BRCA1", "BRCA2"),] %>% dplyr::select(ensembl_gene_id, external_gene_name) ## Getting BRCA gene information
brca <- gdc_gene_exp_adj %>% .[rownames(.) %in% brca$ensembl_gene_id, ] %>% ## we only want brca gene
  rownames_to_column(var = "ensembl_gene_id") %>%
  left_join(., brca, by = "ensembl_gene_id") %>% 
  remove_rownames()  %>% column_to_rownames(var = "external_gene_name") %>% ## replace ensembl_id with gene_name
  dplyr::select(-ensembl_gene_id) %>% ## get ride of ensembl_id  col
  t() %>% as.data.frame() %>% ## correct orientation for umap_cancertype df
  rownames_to_column(var = "V1") %>% ## getting data ready for leftjoin 
  mutate(BRCA1 = case_when(BRCA1 == "1" ~ "BRCA1",
                           BRCA1 == "0" ~ "NA"),
         BRCA2 = case_when(BRCA2 == "1" ~ "BRCA2",
                           BRCA2 == "0" ~ "NA")) %>%
  mutate(mut_type = gsub('NA,|,NA', '', paste(.$BRCA1, .$BRCA2, sep = ","))) %>% ## combine mutation cause some patients can have both
  dplyr::select(-BRCA1, -BRCA2) %>% ## remove col we don't need
  left_join(., umap_cancertype[,c("V1", "x_2d", "y_2d", "project_code")], by = "V1") ## leftjoin by sample id

fig1J <- ggplot(brca %>% filter(mut_type != "NA"), aes(x = x_2d, y = y_2d, colour = mut_type)) +
  geom_point(data = brca, aes(x = x_2d, y = y_2d), colour = "grey") +
  geom_point() + 
  theme_classic() +
  ylab("umap_2") +
  xlab("umap_1") +
  labs(color = "", tag = "J") +
  scale_color_manual(labels = c("BRCA1", "BRCA1,BRCA2", "BRCA2"), 
                     values = c('#33a02c', '#e31a1c', '#ff7f00')) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.ticks = element_blank(),
        legend.position = "bottom")

## umap stage
fig1K <- ggplot(subset(umap_cancertype, ajcc_pathologic_tumor_stage != "Not Available"), aes(x = x_2d, y = y_2d, colour = ajcc_pathologic_tumor_stage)) +
  geom_point(data = umap_cancertype, aes(x = x_2d, y = y_2d), colour = "grey") +
  geom_point() + 
  theme_classic() +
  ylab("umap_2") +
  xlab("umap_1") +
  labs(tag = "K", color = "") +
  scale_color_manual(labels = c("Stage I", "Stage II", "Stage III", "Stage IV"), 
                     values = c('darkgoldenrod3','dodgerblue3','yellow3','tomato2')) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.ticks = element_blank(),
        legend.position = "bottom") 

## umap metastasis
fig1L <- ggplot(umap_cancertype, aes(x = x_2d, y = y_2d)) +
  geom_point(data = umap_cancertype, aes(x = x_2d, y = y_2d), colour = "grey") +
  geom_point(data = subset(umap_cancertype, ajcc_metastasis_pathologic_pm == "M0"), aes(x = x_2d, y = y_2d, colour = ajcc_metastasis_pathologic_pm)) + 
  geom_point(data = subset(umap_cancertype, ajcc_metastasis_pathologic_pm == "M1"), aes(x = x_2d, y = y_2d, colour = ajcc_metastasis_pathologic_pm)) + 
  ylab("umap_2") +
  xlab("umap_1") +
  labs(tag = "L", color = "") +
  scale_color_manual(labels = c("M0", "M1"), 
                     values = c('#a6cee3','#1f78b4')) +
  theme_classic() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.ticks = element_blank(),
        legend.position = "bottom")

layout <- '
AAAABBCCDD
AAAAEEEFFF
AAAAGGGGGG
AAAAGGGGGG
AAAAHHIIJJ
AAAAKKLL##
'

fig1A + plot_spacer() + fig1C + plot_spacer() + fig1E + fig1F + fig1G + fig1H + fig1I + fig1J + fig1K + fig1L + plot_layout(design = layout)

```
