<div style="text-align: right"> Supplementary Figure ST1 Data </div>
```{r supplemental-table-st1-data-generation, eval = FALSE}
load("../data/gdc_tumor_coding_complete.Rdata")
load("../data/gdc_reactome_path_analysis.Rda")
load("../data/gene2_level2_lookup.Rda")
load("../data/pathname2level2.Rda")
load("../data/gene_data.Rda")
load("../data/gdc_gene_exp_adj.Rda")

## Parameters ##
n_path <- 377 ## how many top pathways do you want to see. 1 = top path, 2 = top path and second most
mutated_gene_position <- c(1,2,3) ## what gene do you want to see. 1 = top gene, 2 = second most, 3 = third
show_perc <- TRUE ## show perc for mutated gene


toppath <- gdc_reactome_path_analysis %>% rowSums() %>% as.data.frame() %>% rownames_to_column(var = "path_name") %>% arrange(desc(.)) %>% .[1:n_path,] %>% .[, "path_name"] ## getting the top mutated pathways

id_to_names <- gene2level2_lookup %>% rownames_to_column(var = "ensembl_gene_id") %>% ## convert ensembl to gene name
  left_join(., gene_data[,c("ensembl_gene_id", "external_gene_name")], by = "ensembl_gene_id") %>%
  remove_rownames() %>% column_to_rownames(var = "external_gene_name") %>%
  dplyr::select(-ensembl_gene_id) %>%
  t() %>% as.data.frame() %>% rownames_to_column(var = "PATH_ID") %>% ## convert path_id to path_name
  left_join(., pathname2level2, by = "PATH_ID") %>%
  remove_rownames() %>% column_to_rownames(var = "PATH_NAME") %>%
  dplyr::select(-PATH_ID) %>%
  t() %>% as.data.frame()

gene_mutation <- gdc_gene_exp_adj %>% rownames_to_column(var = "ensembl_gene_id") %>% ## convert ensembl to gene name
  left_join(., gene_data[,c("ensembl_gene_id", "external_gene_name")], by = "ensembl_gene_id") %>%
  remove_rownames() %>% column_to_rownames(var = "external_gene_name") %>%
  dplyr::select(-ensembl_gene_id)

table_st1 <- list() ## list for forloop 

for(n in toppath) {
  message(n)
  ## finding top mutated gene in pathway
  gene_in_path <- id_to_names %>% .[,which(names(.) == n)] %>% as.data.frame() %>% ## select pathway
    'rownames<-' (rownames(id_to_names)) %>% 
    filter(. == 1) %>% ## filter for genes that are in that pathway
    rownames(.)
  top_mut_gene <- gene_mutation %>% .[rownames(.) %in% gene_in_path, ] %>% ## only include genes in paths
      rowSums() %>% as.data.frame() %>% 'colnames<-' ("obs_count") %>% ## sum the pathway mutation
      mutate(n_sample = length(gene_mutation),
             perc_mut = round((obs_count / length(gene_mutation)) * 100, digits = 1)) %>% 
      rownames_to_column(var = "gene") %>% arrange(desc(obs_count))
  top_gene_in_path <- list()
  for(p in mutated_gene_position) {
    message(p)
    if(show_perc == TRUE) {
    top_gene_in_path[[p]] <- paste0(top_mut_gene$gene[p], " (", top_mut_gene$perc_mut[p],"%)")  
    }
    if(show_perc == FALSE) {
    top_gene_in_path[[p]] <- paste0(top_mut_gene$gene[p])  
    }
  }
  top_gene_in_path <- top_gene_in_path %>% do.call(rbind, .) %>% as.data.frame() %>% ## rbind list
   'rownames<-' (mutated_gene_position) %>% t() %>% as.data.frame()
  ## calculating the percent mutated samples
  spec_path <- data.frame(Pathway = n,
                          Percent_Mutated = round(gdc_reactome_path_analysis %>% .[n,] %>% sum() / length(gdc_reactome_path_analysis) * 100, digits = 1))
  table_st1[[n]] <- cbind(spec_path, top_gene_in_path)
}
table_st1 <- as.data.frame(do.call(rbind, table_st1))
save(table_st1, file = "table_st1.Rda")  
rm(list = ls(all.names = T))  
gc()
```

```{r supplemental-table-st1}
load("../data/table_st1.Rda")

table_st1 %>% dplyr::select(-Pathway) %>% knitr::kable(format = "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE, font_size = 12) %>%
  column_spec(1, bold = T, color = "black")
```