<div style="text-align: right"> Table 2 Data </div>
```{r table-2-data-generation, eval = FALSE}
tumor_clusters <- fread("../data/umap_2d_3d_coors.tsv") ## load in data
load("../data/gdc_reactome_path_analysis.Rda")

tumor_clusters <- tumor_clusters %>% dplyr::select(V1, ajcc_metastasis_pathologic_pm, knn_clust)

m0_clust <- tumor_clusters[tumor_clusters$ajcc_metastasis_pathologic_pm == "M0",] ## filter for nonmetastatic samples
m1_clust <- tumor_clusters[tumor_clusters$ajcc_metastasis_pathologic_pm == "M1",] ## filter for metastatic samples

prepare_rbeta_data_p1 <- function(data, path_analysis) {
  n_tumor_in_group <- as.data.frame(table(data$ajcc_metastasis_pathologic_pm)) ## Getting the total number of tumor samples in each group
  path_analysis <- path_analysis[,names(path_analysis) %in% data$V1] ## Filter only group specific cancers
  data <- data[match(names(path_analysis), data$V1),] ## Match tumor sample ids
  table(names(path_analysis) == data$V1) ## good they match now
  ## Now we are going to build group specific cluster data
  n_tumor_in_clust <- as.data.frame(table(data$knn_clust)) ## getting total n in each cluster
  names(n_tumor_in_clust) <- c("clust", "tot_n_clust") ## rename colnames
  clust_group <- as.character(n_tumor_in_clust$clust) ## Getting the cluster numbers
  cluster_path_count <- list() ## Creating a list for the forloop
  for(n in clust_group) {
    print(n)
    df <- subset(data, knn_clust == n) ## subset cluster number
    df <- df$V1 ## getting tumor sample id
    df1 <- path_analysis[,names(path_analysis) %in% df] ## getting the tumor samples from path analysis
    df1 <- as.data.frame(rowSums(df1))
    names(df1) <- n
    cluster_path_count[[n]] <- df1
  }
  cluster_path_count <- do.call(cbind, cluster_path_count) ## Combine the list together
  rbeta_path_df <- cluster_path_count %>% rownames_to_column(var="path") 
  rbeta_path_df <- rbeta_path_df %>% gather(key = "clust", value = "mutation", -path) ## Wide to long format
  global_path_mut <- as.data.frame(rowSums(cluster_path_count))
  global_path_mut <- global_path_mut[rep(1:ncol(global_path_mut), each = max(as.numeric(as.character(rbeta_path_df$clust))))] ## Repeat column 12 times
  names(global_path_mut) <- as.character(clust_group) ## Replace names with cluster numbers
  global_path_mut <- global_path_mut %>% rownames_to_column(var="path") %>% gather( key = "clust", value = "global", -path) ## Wide to long format
  rbeta_path_df <- left_join(rbeta_path_df, global_path_mut, by = c("path", "clust")) ## left_join rbetadf and global
  rbeta_path_df <- left_join(rbeta_path_df, n_tumor_in_clust, by = "clust")
  rbeta_path_df$global_sample <- as.numeric(sum(n_tumor_in_clust$tot_n_clust)) ## Getting total tumor sample number
  names(rbeta_path_df) <- c("path", "clust", "clust_mut", "global_mut", "tot_n_clust", "global_sample")
  rbeta_path_df$tot_n_clust <- as.numeric(as.character(rbeta_path_df$tot_n_clust)) ## convert tot_n_clust numeric
  return(rbeta_path_df)
}

m0_rbeta <- prepare_rbeta_data_p1(data = m0_clust, path_analysis = gdc_reactome_path_analysis)
## Combining cluster 6/7 cluster 910 cluster 1112
combo_group <- c("6", "9", "11")
compo_group_df <- list() ## list for loop
for(n in combo_group) {
  print(n) ## first cluster in set
  m <- as.numeric(n) + 1 ## second cluster in set
  m <- as.character(m)
  df <- m0_rbeta[m0_rbeta$clust == n,] ## get rbeta info for first cluster in set
  df1 <- m0_rbeta[m0_rbeta$clust == m,] ## get rbeta info for second cluster in set
  tot_clust_mut <- df$clust_mut + df1$clust_mut ## add both clust muts
  tot_n_clust <- df$tot_n_clust + df1$tot_n_clust ## add both clust n's
  p <- paste0(n,m)
  df2 <- m0_rbeta[1:377,]
  df2$clust <- p ## replace with new clust name
  df2$clust_mut <- tot_clust_mut ## replace with new clust mut count
  df2$tot_n_clust <- tot_n_clust ## replace with new clust size
  compo_group_df[[p]] <- df2 ## store in list and continue loop
}
compo_group_df <- do.call(rbind, compo_group_df) ## rbind list
m0_rbeta <- rbind(m0_rbeta, compo_group_df) ## rbind m0_rbeta and the compo group together
save(m0_rbeta, file = "m0_rbeta.Rda")

## repeat same function above with metastasis sample
m1_rbeta <- prepare_rbeta_data_p1(data = m1_clust, path_analysis = gdc_reactome_path_analysis)
compo_group_df <- list() ## list for loop
for(n in combo_group) {
  print(n) ## first cluster in set
  m <- as.numeric(n) + 1 ## second cluster in set
  m <- as.character(m)
  df <- m0_rbeta[m0_rbeta$clust == n,] ## get rbeta info for first cluster in set
  df1 <- m0_rbeta[m0_rbeta$clust == m,] ## get rbeta info for second cluster in set
  tot_clust_mut <- df$clust_mut + df1$clust_mut ## add both clust muts
  tot_n_clust <- df$tot_n_clust + df1$tot_n_clust ## add both clust n's
  p <- paste0(n,m)
  df2 <- m0_rbeta[1:377,]
  df2$clust <- p ## replace with new clust name
  df2$clust_mut <- tot_clust_mut ## replace with new clust mut count
  df2$tot_n_clust <- tot_n_clust ## replace with new clust size
  compo_group_df[[p]] <- df2 ## store in list and continue loop
}
compo_group_df <- do.call(rbind, compo_group_df) ## rbind list
m1_rbeta <- rbind(m1_rbeta, compo_group_df) ## Combine the new groups
save(m1_rbeta, file = "m1_rbeta.Rda")

## function to compiling data for rbeta analysis
prepare_rbeta_data_p2 <- function(data) {
  enrich_prob <- data.frame(path = data$path,
                               clust = data$clust,
                               fg_mut = data$clust_mut,
                               fg_not_mut = data$tot_n_clust - data$clust_mut,
                               bg_mut = data$global_mut,
                               bg_not_mut = data$global_sample - data$global_mut)
fg_mut_rate <- list()
bg_mut_rate <- list()
for(n in unique(as.character(enrich_prob$clust))) {
  print(n)
  df <- subset(enrich_prob, clust == n)
  fg_denominator <- nrow(df) * (df$fg_mut[1] + df$fg_not_mut[1]) ## n_path * tot_n_clust_x
  fg_numerator <- sum(df$fg_mut)
  bg_denominator <- nrow(df) * (df$bg_mut[1] + df$bg_not_mut[1])
  bg_numerator <- sum(df$bg_mut)
  fg_mut_rate[[n]] <- fg_numerator / fg_denominator
  bg_mut_rate[[n]] <- bg_numerator / bg_denominator
}

fg_mut_rate <- as.data.frame(do.call(rbind, fg_mut_rate)) ## rbind the mut rates from list
bg_mut_rate <- as.data.frame(do.call(rbind, bg_mut_rate)) ## rbind the mut rates from list
enrich_prob_df <- enrich_prob
enrich_prob_df$fg_mut_rate <- rep(x = fg_mut_rate$V1, each = length(unique(enrich_prob_df$path)))
enrich_prob_df$bg_mut_rate <- rep(x = bg_mut_rate$V1, each = length(unique(enrich_prob_df$path)))
enrich_prob_df$rel_odds <- enrich_prob_df$fg_mut_rate / enrich_prob_df$bg_mut_rate
enrich_prob_df$denominator <- (enrich_prob_df$bg_mut * enrich_prob_df$rel_odds) +   (enrich_prob_df$bg_not_mut / enrich_prob_df$rel_odds)
enrich_prob_df$x_adj <- round((enrich_prob_df$fg_mut + enrich_prob_df$fg_not_mut) * (enrich_prob_df$bg_mut * enrich_prob_df$rel_odds) / enrich_prob_df$denominator)
enrich_prob_df$y_adj <- (enrich_prob_df$fg_mut + enrich_prob_df$fg_not_mut) -   enrich_prob_df$x_adj
return(enrich_prob_df)
}

m0_rbeta <- prepare_rbeta_data_p2(m0_rbeta)                               
m1_rbeta <- prepare_rbeta_data_p2(m1_rbeta)     

save(m0_rbeta, m1_rbeta, file = "m0_m1_rbeta.Rda")
rm(list = ls(all.names = T)) ## cleaning up data
gc()
load("../data/m0_m1_rbeta.Rda")
## Metastatic (foreground) - Nonmetastatic (background) Rbeta
moderate_fg <- apply(m1_rbeta[,c("fg_mut", "fg_not_mut")], MARGIN = 1, function(x) {
  rbeta(n = 1e5, shape1=x["fg_mut"], shape2=x["fg_not_mut"])
})
moderate_bg <- apply(m0_rbeta[,c("fg_mut", "fg_not_mut")], MARGIN = 1, function(x) {
  rbeta(n = 1e5, shape1=x["fg_mut"], shape2=x["fg_not_mut"])
})

metastasis_cluster_moderate <- moderate_fg - moderate_bg  ## Fg - Bg ... to see how many times the Fg is larger than the Bg
metastasis_cluster_moderate <- as.data.frame(metastasis_cluster_moderate)

## ModerateEnrichment probability 
prob <- moderate_fg > moderate_bg ## boolean data
mean_prob <- apply(prob, MARGIN = 2, function(x) {
  mean(x)
})
## Moderate Difference
CI <- 0.025

diff_fg_bg <- moderate_fg - moderate_bg ## fg - bg
rm(moderate_fg, moderate_bg, prob)
gc()
quant_diff <- t(apply(diff_fg_bg, MARGIN = 2, function(x) {
  quantile(x, c(CI, 0.5, 1-CI)) ## 95% CI
}))

sig_fg_bg <- as.data.frame(apply(diff_fg_bg, MARGIN = 2, function(x) {
  sum(x < 0 ) ## out of 1e5 simulations, how many times is fg-bg less than 0
}))

m1_minus_m0_per_cluster_rbeta <- data.frame(path = m1_rbeta$path,
                                   clust = m1_rbeta$clust,
                                   probability = mean_prob,
                                   signif = sig_fg_bg[,1],
                                   difference = quant_diff[,2],
                                   lower = quant_diff[,1],
                                   upper = quant_diff[,3])
save(m1_minus_m0_per_cluster_rbeta, file = "m1_minus_m0_per_cluster_rbeta.Rda")
rm(list = ls(all.names = T))
gc()
```

```{r table-2}
load("../data/m1_minus_m0_per_cluster_rbeta.Rda")

table2 <- m1_minus_m0_per_cluster_rbeta %>% filter(difference >= 0.20 & signif <= 2500) %>% ## filter effect size >= 0.20 and enrichment at a 95% CI
  dplyr::select(path, clust, signif, difference) %>% 'colnames<-' (c("Pathway", "Cluster", "Signif", "Enrichment_Score")) ## select relevant column and rename col

table2$log10pvalue <- round(-log10((table2$Signif + 1) / 1E5), digits = 2) ## Getting p value ## adding 1 for pseudo count.. 1E5 is the n simulations performed
table2$Enrichment_Score <- round(table2$Enrichment_Score, digits = 2)
table2$Signif <- NULL ## we don't need this anymore

table2 %>% knitr::kable(format = "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE, font_size = 12) %>%
  column_spec(1, bold = T, color = "black")
```